---
title: "Armeria, benvenuti dal fabbro"
output-file: armeria.html
format:
  html:
    theme: default
---

## **Armi Bianche**

| **Nome** | **Danno**   | **Descrizione** | **Costo Indicativo** |
| ---- | ---- | ---- | ---- |
| Coltello| 3 taglienti | - | 5k  |
| Spada Corta  | 6 taglienti | Possibilità di effettuare Disarmo e Destreggiarsi (se possedute)| 15k  |
| Ascia da guerra | 4 taglienti + Forza | Impugnabile con competenza spada corta  | 25 k |
| Martello a una mano | 5 contundenti | Se il possessore ha almeno 3 a Forza ottiene +1 al danno. | 16k                  |
| Spada da lato | 6 taglienti | Possibilità di effettuare disarmo e Destreggiarsi (se possedute)<br><br>Se tira in difesa ottiene contrattacco (non critico) anche con 19.<br><br>Ha vantaggio ai tiri di contrattacco e Disingaggio | 30K  |
| Spada lunga a una mano | 8 taglienti | Possibilità di effettuare disarmo e Destreggiarsi (se possedute) | 20k  |
| Spada lunga _due mani_ | 9 taglienti | Possibilità di effettuare disarmo (se si possiede la Manovra) con vantaggio, o Destreggiarsi.<br><br>Aumento al tiro per schivare di 3, se non ingaggia contro un’altra arma a _due mani_.<br><br>Critico con 18, 19 o 20 se il  possessore ha 6 a Destrezza. | 35k                  |
| Ascia bipenne _due mani_    | 9 taglienti/<br>+ Forza | - | 50k |
| Martello pesante _due mani_ | 7 Contundenti | Richiede 1 di Forza.<br><br>Se il possessore ha almeno 2 a Forza ottiene +1 al danno.<br><br>Critico con 19 o 20 se il possessore ha almeno 3 Forza.<br><br>Colpire 3 volte un nemico con quest’arma genera stunn (al prossimo turno l’avversario non effettua Azione) | 30k                  |
| Lancia (_Due mani)_ | 10 perforanti | Richiede 1 Forza, ottiene +3 al tiro schivare contro tutte le armi in mischia. Se contrattacchi con parry, o attacchi con attacco furtivo o attacco inaspettato, critti con 18, 19, 20. | 16k                  |

## **Armi a Distanza**

| **Nome** | **Danno**     | **Descrizione**                         | **Costo Indicativo** |
| ------------------- | ------------- | --------------------------------------- | -------------------- |
| Coltello da lancio  | 2 taglienti   | 20m gittata                             | 5k                   |
| Arco corto          | 4 perforanti  | 90m gittata                             | 20k                  |
| Balestra            | 6 perforanti  | 150m (richiede un turno per ricaricare) | 70k                  |
| Arco lungo          | 8 perforanti  | 200m gittata (almeno 0 a Forza)         | 40k                  |
| Giavellotto         | 10 perforanti | 12m gittata (almeno 1 Forza)            | 15k                  |

Ogni altra arma può essere offerta come una skin diversa di queste armi, o come una personalizzazione di alcune di queste caratteristiche.

## **Armature e Scudi**

| **Nome** | **Descrizione** | **Costo Indicativo** |
| -------------------- | --------------- | -------------------- |
| Scudo piccolo  | Ogni colpo in mischia che passa viene parato con 1 su 1d6 | 20k    |
| Scudo grande  | Ogni colpo in mischia che passa viene parato con 1-2-3 su 1d8.<br><br>Difende in questo modo (tirando) anche da fiancheggi ed opportunità.<br><br>2 Forza richiesto. | 40k   |
| Armatura leggera | -2 Danni taglienti<br><br>-1 agli altri tipi di danno.  | 70k    |
| Armatura media | -4 Danni taglienti<br><br>-2 Danni perforanti<br><br>-2 Danni pesanti | 100k                 |
| Armatura pesante | -5 Danni taglienti<br><br>-4 Danni perforanti<br><br>-3 Danni pesanti<br><br>Necessita 2 Forza                                                                       | 200k                 |


## Armi da fuoco 

| **Nome**      | **Danno**         | **CD**            | **Portata massima** | **Colpi** |
| ------------- | ------------------ | ----------------- | ------------------- | -------------------- |
| Pistola       | 7 perforanti       | +1 ogni 20 metri  |      200m              |      6 Colpi   |
| Fucile        | 10 perforanti       | +1 ogni 100 metri | 700m                 | 4 Colpi              |
| Gran Bastardo | 16 perforanti (danno doppio se ingaggiato corpo a corpo) | +1 ogni 5 metri   | 30m | 1 Colpo   |
NB: Ricaricare costa un'azione 