---
title: "Collezionista Arcano"
format:
  html:
    theme: default
---

%PAGINA IN COSTRUZIONE%

Questo negozio contiene una serie di oggetti dai vari usi, più o meno rari, più o meno magici. Con tutta probabilità, sono gestiti da un aspirante Arcanista.

**Importante**, non tutte le città ne hanno uno. Chiaramente dovete chiedere al DM.
Dal Collezionista molti oggetti saranno dei falsi o per nulla magici. È pertanto importante che sia possibile avere conferma con percezione del magico.

Tutti gli oggetti hanno *Autorità 4.1*

### Classe Trucco
- Fuochi di Katrina: libera un fuoco d'artificio
- Fumogeno di Maka: libera un fumogeno che blocca la visuale intorno a un'area di 6 metri di raggio

### Classe Rubik
- Lente del rimpianto: con questa puoi leggere solo cose che sono state cancellate da una superficie scrivibile. 
- Maschera di Rulah: riesci a respirare evitando veleno nell'aria 
- Lanterna del Lupin: la luce di questa lanterna non è individuabile a chi sia a più di 2m dalla lanterna
- Barattolo lunga forma: qualcosa di contenuto qui dentro non deperisce
- Filo delle Parche: una bobina con 400 metri di filo molto sottile, che può essere tagliato solo da quelle forbici 

### Classe Enigma 
- Perle piene di Malascen: può coutnerare un incantesimo, rompendo  la perla
- Ghiandaia sentinella: questo piccolo uccello magico si lega al suo propietario. Inizia a canticchiare quando qualcuno ti sta origliando
- Forziere dei pirati: quando qualcosa viene nascosto qui dentro, chiunque si scorda di cosa fosse quel qualcosa, ma da che c'è qualcosa.
- Sfera atmosfera: una sfera di vetro appesa a una bella catena d'argento, all'iterno della quale ruota del pulviscolo, che assume le fattezze del meteo attuale. È possibile ruotare l'aggancio e fare variare il meteo.
- Bacio di Vengra: quante volte vuoi durante il tuo turno, il master tira 1d20. Se fai <1 guadagni 1d6 pf. Se fai 1 perdi 2 pf per ogni volta in cui hai mai lanciato il dado. (NB: Autorità 2)
- Libro di non-dove: se lasci una pagina del libro in un posto le persone all'interno sono perse. L'effetto termina nell'istnate in cui viene staccata dal muro, (e se viene riattaccata comunqeu ha perso il suo effetto)
- Segnatempo del mago: con un'azione o reazione puoi riscrivere  l'ordine dei turni dei giocatori, al rpezzo di 1d6 pf. 
- Portagioie vitale: puoi segnarti i tuoi pf e condizioni di stato di adesso. Puoi spendere un'azione bonus, cancellare quello status e tonrare a quello status.  Se attivi ancora questa capacità durante la stessa giornata, perdi 2 pf permamenti a riprisitino.
- Orologio di Rulah: per il tempo in cui viene attivato l'orologio passi inosservato finché non parli con qualcuno. L'orologio conserva 1 ora tutti i giorni e le accumula. 
- Teschio di Vengra: se conosci le perole per dire in Ingvio "Nostra Signora" il teschio lascerà un fumo nero molto denso che riempirà una stanza in tre turni. TUtti quelli con scurovisione o scurovisione minore vedono massimo entro 3 metri, lo stesso vale per quelli con la luce. Se hai Occhio Arcano ci vedi lo stesso.
- Lunga pipa di Odino: fumando questa pipa al contrario rilascia una enorme quantità di fumo. Pagando 2 danni ogni turno ci vedi. Nessun'altro vede niente (se non con Occhio arcano). Il fumo è denso e pesante, si disperde da quanto smetti di fumare in una trentina di secondi.

### Classe Mistero 
- Pennello di Rikka: devi comprare l'inchiostro, si misura in unità di disegno. (1 boccetta materiale base cioè tipo legno e corda 5 unità di disegno, acciaio e ferro a 5 oro a boccetta.)
- Orologio del Banchiere: se non fai niente per un tot numero di ore, puoi accumulare dette ore. In qualsiasi momento puoi attivare l'orologio e investire tot ore storate in una attività ripetitiva, per la quale non devi fare grandi sforzi mentali (eccetto leggere). Non puoi castare in dette attività. (sicuramente, se c'è una prova di mezzo prevede uno sforzo mentale)





- Portagioie 






- Qualcosa per bloccare l'inventario. Magari un lucchetto
- Bracciali magnetici: si ferma uno in un punto e l'altro si avvicina
- modulatore della voce (un po' mid)
- item che modifica il tipo di danno di un'arma (perf, tagl, cont) 
- Chiave dad meccanico: Item che può bloccare o sbloccare un ingranaggio o meccanismo (non serrature)
- Sismocettore: consente di rilevare tutte le persone nei dintorni e fare mappa 3D dell'ambiente
- Antison: consente di eliminare tutti i rumori entro una certa portata, vengono annullati
- Lanterna dei segreti: illumina solo cose che sono messe con l'intenzione di non essere viste o ben nascoste
- Contrappeso di parità: bilancia immediatamente una forza, creando un equilibrio perfetto
- Mappa del Labirinto: crea una parete di carta, che sembra però fatta esattamente del materiale di cui la vuoi creare 
- Sonar localizzato: lasci un sonar in una stanza. Puoi sentire con l'altro sonar cosa si sta dicendo 
- iniettacorde: una corda o una catena si muove molto lentamente come tu vuoi che si muova, creando i nodi che intendi