---
title: "Fabbro Magicante"
format:
  html:
    theme: default
---

Dal fabbro magicante è possibile Incantare gli oggetti. 

Per incantare gli oggetti occorre mettersi d'accordo con il fabbro magicante di riferimento sul tipo di incantamento che si desidera e valutarne insieme il costo. Comunque sono operazioni molto costose (quasi mai sotto 300). Inoltre un incantamento prende una notte. 

**Tipi di incanto**
Gli incanti vengono discussi di volta in volta, perché ogni fabbro magicante è a sè. Ci sono però dei fondamentali su cui tutti sonno d'accordo, per cui è molto facile che il fabbor li consoca o li possa eseguire: 
- "Lealtà": l'arma torna volando alla mano del propietario (necessaria un'azine bonus per eseguirla)
- "Tessuto Clairein": è possibile, consegnando sia un abito che un'armatura, a un prezzo elevato, trasferire sull'abito  le caratteristiche anti danno dell'armatura. (rimane un abito però, per dire può bruciare)

**Regole**
- Quando si incanta un'arma, il DM tira un D20, se fa 1 l'incanto fallisce. Il PG paga comunque il prezzo dell'incanto. Occorre ritentare. Se si ottiene 1 tre volte di fila sulla stessa arma, la stessa si rompe. 
- Quando un oggetto ha già 1 magia, e se ne vuole apporre una seconda, se il master fa 1 si perde sia la prima che la vecchia seconda, se il master fa 2,3,4,5 invece la seconda non va a buon fine, e occorre ritentare. 
- Quando si tenta di incantare un'arma con un veleno infuso, il DM ha svantaggio al tiro.
- A meno di armi in metalli particolari, non è possibile apporre più di 2 incanti. 

**Fabbro magicante**
Il fabbro è l'unica persona in grado di incantare le armi e gli oggetti, e nessuno sa come faccia a parte qualcuno che abbia studiato l'arte.

**Sintonizzazione**
Certi incanti potrebbero essere così potenti da richiedere che il propietario esegua un piccolo legame (per il DM, si tratta di Ladega) con l'arma, che rende la sua  mente collegata all'oggetto. Questo legame può essere spento a necessità (no action) e ricreato in 1 azione su un'altro oggetto, ma solo con un oggetto per volta per usare il suo potere.