---
title: "Erboristeria- Veleni"
format:
  html:
    theme: default
---

Gli erboristi sono magici che hanno dedicato la vita ai veleni: la loro creazione, identificazione, ed eventuale vendita. Come tutti i magici di questo mondo, sono sostanzialmente dei tossici: il  motivoo per cui fannno questo lavoro è che produrre magia è come una droga, e lo stesso vale per la produzione e assimilazione dei veleni.

**Autorità**:tipicamente, dove non diversamente specificato, hanno *Autorità: 4.2*.

### Veleni 

#### Acido Agnico 

- *Rarità*: 2/3
- *Prezzo*:25
- *Tipo*: Veleno
- *Disponibilità*:2d4
- *Descrizione*: Tossina ricavata dalla fermentazione delle pelli di molti animali
- *Effetto*: Chiunque venga a contatto diretto col veleno aggiunge 1d4 a tutti i danni che riceve fino a riposo lungo. 

_Infusione_: +35, 5min
L'avversario colpito subisce 1d4 danni per 43 turni ogni volta che subisce danno da un'altra arma. 

#### Acrilica

- *Rarità*: 3/3
- *Prezzo*: 38k
- *Tipo*: Veleno
- *Disponibilità*: 1d10
- *Descrizione*: Viene ottenuto dalla cenere del pelo delle [[Nuvivolpe]]. Ci sono modi perché l'effetto contagi altre code di volpi comuni
- *Effetto*: perdi 1d6 vita permanenti

#### Arlekin

- *Rarità*: 3/3
- *Prezzo*: 70l
- *Tipo*: Veleno
- *Disponibilità*: 1d4 (mensile)
- *Descrizione*: Questo pesce camaleontico affascina magicamente i suoi nemici. SI ottiene fondendo e riducendo le sue ossa. Il pesce dev'essere deliscato mentre ancora vivo. 
- *Effetto*: una creatura colpita tira su Intelligenza contro il propietario: se passa il tiro, questo non considera il porpietario come nemico. Se fallsice lo considera alleato. Ogni volta che il proprietario agisce contro di  lui, ritira. L'effetto dura 3 turni. Se ingerito dura 2 minuti, e hai svantaffio nelle prove sociali contro il propietario. 

*Infusione*: +100k, 2 notti 
Stessi effetti. 

**NB**: una goccia del sangue del propietario va inseirta nel veleno.

#### Arrandro 

- *Rarità*: 2/3
- *Prezzo*: 28 k
- *Tipo*: Veleno
- *Disponibilità*: 2d8
- *Descrizione*: Ottenuto dai [[Cristalli Naturali]] inventati da Eric, l'arcanista
- *Effetto*: Tira su forza 
	- 18-13:  sei sordo
	- 12-9: sei sordo, -3 D, 1/2 movimento 
	- >8: sei sordo, -3 D  e sei immobilizzato 
 Per 4 ore

  **NB**: se sei sotto [[Antiveleno]] ne sei immune 

*antidoto* 
- Dirmorfa
- Alloro Bianco
- Ultima Ombra

#### Belladonna

- *Rarità*: 1/3
- *Prezzo*: 36k
- *Tipo*: Veleno
- *Disponibilità*: 2d4 
- *Descrizione*: Estratto dal fiore di Belladonna Rossa, facilmente reperibile in boschi dai climi anche poco temperati
- *Effetto*: a ogni sforzo fisico significativo (anche brandire un'arma, ma non parlare o camminare) subisci 1d6 danni. Fino a fine giornata. 

*Antidoto noto*: [[Alloro Bianco]]

*Infusione*: +25k, 1/2 giornata
Colpito da questo veleno infuso, per 1 ora subisci 1d4 danni ogni 9 m di movimento, a meno di camminare molto lentamente. 

#### Bradefrina

- *Rarità*: 2/3
- *Prezzo*: 38K
- *Disponibilità*: 2d6
- *Descrizione*: uno dei veleni partoriti dagli studi sul sangue per combattere vampiri e dragonidi
- *Effetto*: tira su  Forza con CD 17, se non passi subisci 1d6 danni, perdi 1 forza e destrezza e mezza distanza di movimento. ogno colpo che infliggi fa 4 danni in meno. Hai svatnaggio a colpire a distanza (1h)
	- Se iniettato con un'arma in argento raffinato, ha effetto sui vampiri
	- se eri sotto "Tormentina" l'effetto d8iiventa; non puoi fallire una prova di mascheramento  emotivo, non puoi venire spaventato o affasccinato. 
- Antidoti: fobefrina, acrilica

#### Fobefrina

- *Rarità*: 2/3
- *Prezzo*: 29k
- *Disponibilità*: 2d6
- *Descrizione*: uno dei veleni partoriti dagli studi sul sangue per combattere vampiri e dragonidi
- *Effetto*: TIa su Forza  CD 17, se fallisci attacchi indistintamente la persona più vicina. Hai mezza distanza in aggiunta al movimento, + 2 Forza e aggiungi Forza ai danni. Aggiungi +1 a Destrezza per ogni 6 pf di distanza dai tuoi pf massimi. Subisci 4 danni aggiuntivi se ricevi danni taglienti. (1h)
	- Questo veleno ha effetto sui vampiri se si colpisce con arma in argento raffinato
	- Se chi viene avvelenato era sotto "tormentina" gli effetti sono i seguenti: ottieni +5 moviemnto e 2 attacchi a round. Alla fine del combattimento o dopo  1 minuto subisci 1d6 danno per ogni colpo che hai ricevuto mentre questo veleno era in circolo. 
- Antidoto: bradefrina. 

#### Désiem 

- *Rarità*: 2/3
- *Prezzo*: 38k
- *Tipo*: Veleno
- *Disponibilità*: 2d6
- *Descrizione*: Un paralizzante ottenuto da radici lasciate riposare in spcifici cicli lunari. spesso però non funzionano, l'unica è testarle ogni volta
- *Effetto*: 
	- Un arto a casa viene paralizzato per 1d4 ore. (lo stesso flacone paralizza sempre lo stesso arto)
	- Se si ha la resistenza ai veleno o si è sotto [[Antiveleno]] non ha effetto

#### Dirmorfa

- *Rarità*: 3/3
- *Prezzo*: 30k
- *Tipo*: Veleno
- *Disponibilità*: 2d6
- *Descrizione*: Ottenuto dall'essicazione di coralli sviluppati in baie abitate da [[Sirene]]
- *Effetto*: Bevendo o inalando  (se disperso in ambiuente ad alta temperatura) fai una prova di Forza con CD 18. Se non passi entru 1h svieni 

**NB**: il sapore e odore dolciastro vengono identificati facilmente. Una dose dispersa in ambiente copre efficaciemente una piccola distanza (5x5x3). Se hai bevuto [[Acrilica]] oggi, ne sei immune.

#### Endodardo

- *Rarità*: 1/3
- *Prezzo*: 40k
- *Tipo*: Veleno
- *Disponibilità*: 2d6
- *Descrizione*: Ottenuto dalla resida dei [[Pioppi Violetta]] vibra leggermente a contatto con l'acciaio
- *Effetto*: 
	- un'arma con applicato questo veleno non infuso, ignora armature e resistenzee ai danni 
	- se applicato in una serratura delicata la rompe, rendendo impossibile l'apertura tradizionale

#### Fiele del Surdan

- *Rarità*: 3/3
- *Prezzo*: 78k
- *Tipo*: Veleno
- *Disponibilità*: 1d6
- *Descrizione*: Dagli alveari della [[Vespa Amaranto]] del Surdan si estrae questo veleno che causa una violenta reazione allergica
- *Effetto*: per 1 minuto a ogni round tiri 1d4
	- 1: passi la tua azione a vomitare
	- 2-3: perdi 1 d6 danni 
	- 4: perdi 1d4 danni 
	(non puoi scendere sotto i 5 pf, ma se arrivi a 5 fai automaticamente 1)
	
#### Filtro Nero

- *Rarità*: 3/3
- *Prezzo*: 75k
- *Tipo*: Veleno
- *Disponibilità*: 1d6
- *Descrizione*: Estratto della coda del [[Cracken di fiume]], molto difficile da estrarre
- *Effetto*: 
	- Per dure ore hai -2 D
	- Poi svieni 
	- Entro 48h muori 

*Antidoto*: Pasta di Violette

#### Fluido Nesfico 

- *Rarità*: 1/3
- *Prezzo*: 20k
- *Disponibilità*: 3d6
- *Descrizione*: foglia dei Platani di Aronne, il re matto. Può essere fumata come allucinogeno, in forma di foglie, in quei casi offre una visione speciale al giocatore. Altrimenti ne si estrae gli olii essenziali per produrre il fluido dalla corteccia.
- *Effetto*: 
	- Foglie fumate: puoi avere una visione simile al sogno bardico, ma questa sarà solo riguardo a temi del background del giocatore. 
	- Olii:  questa notte non guadagni benefici da riposo lungo, nè questa giornata da quello breve. Gli incubi ti tormenteranno. 
		- NB: se avevi bevuto "Antiveleno" o hai Resistenza ai veleni, puoi tirare su Costituzione CD 15 per annullare gli effetti.


#### Illantina 

- *Rarità*: 2/3
- *Prezzo*: 42 k
- *Disponibilità*: 2d6
- *Descrizione*: ottenuto dalla cresta di un Neythune, ragno tessitore di ricordi, estraendone il veleno.
- *Effetto*: tira su Costituzione (CD 19). Se fallisci non puoi eseguire tiri di Concenza nè provare a ricordare informazioni non immediatamente disponibili fino a riposo lungo. 
	- Se viene iniettato con una siringa d'argento raffinto in alte dosi a un vampiro (almeno 2 dosi), questo deve tirare la stessa Costituzione per usare l'aura (1 min). 

#### Lacrime di Mezzanotte

- *Rarità*:2/3
- *Prezzo*: 48k
- *Tipo*: Veleno
- *Disponibilità*: 2d4
- *Descrizione*: Una forte pulsazione infiammatoria colora le vene di violaceo
- *Effetto*: Allo scoccare della mezzanote tira su Forza con CD 17
	- Passi: subisci 4d8
	- Non passi: subisci 6d8 e non guadagni pf del riposo lungo

*Antidoto*: 
-  Ocra di Serpe
- Fiore di Glicine Marmoreo

#### Malascen 

- *Rarità*: 3/3
- *Prezzo*: 80k
- *Disponibilità*: 1d4
- *Descrizione*: Una rara pianta sorge spontanea dopo che sono stati usati tanti effetti magici in un luogo. Dal miele che le api ne ricavano, una famose strega formò un veleno a cui diede il proprio nome.
- *Effetto*: Non puoi effettuare capacità magiche fino a riposo breve. Se sei in grado di castare, ogni volta devi tirare Costituzione (CD 18). Se ne vengono assunte 3 dosi, non sei in grado di parlare fino a riposo breve. 
	- Se avevi "antiveleno" o resistenza ai veleni ne sei immune. 
	- Infusione: non puoi attivare capacità magiche o di casting per 3 turni, tranne che passando CD 16 costituzione ogni volta.

#### Ocra di Serpre

- *Rarità*: 3/3
- *Prezzo*: 140k
- *Tipo*: Veleno
- *Disponibilità*: 1d4
- *Descrizione*: Veleno della Vipera Gialla  originaria del Sud. Vipera rara e difficile da allevare. Il veleno ossida e si neutralizza all'aria aperta se non ben trattato. 
- *Effetto*: Entro 12 secondi sei paralizzato per 1h. 

*Infusione*: +120k,  1 notte
Stessi effetti, ma dura 1 minuto

**Nota di vendita**: questo veleno viene venduto solo a Cacciatore di bestie certificati dei Venatores, o a persone in possesso di un'autorizzazione nel contesto specifico. 

In alternativa viene venduto al mercato nero coi giusti agganci al triplo del prezzo

#### Sangue di Basilisco

- *Rarità*: 2/3
- *Prezzo*: 70k
- *Tipo*: Veleno
- *Disponibilità*: 2d4 (settimanale)
- *Descrizione*: Un denso liquido rosso dal sapore di aceto. Ottenuto dalle fermentazione e filtraggio del sangue.
- *Effetto*: Chi  lo assume fa una prova di costituzione con CD 19, se fallisce attacca furiosament esenza distinguere nemici o amici. Dura 1d6 turni.
**NB**: se hai bevuto [[Acrilica]] oggi, fallisci la prova e l'effetto dura un'ora

#### Ultima Ombra

- *Rarità*: 2/3
- *Prezzo*: 67k
- *Tipo*: Veleno
- *Disponibilità*: 2d4
- *Effetto*: 
	- chiunque entri a contatto (ferita o ingestione) per 6 ore
		- non può recuperare pv tramite pozioni
		- se bevi una pozione subisci 1d6 danni 
	- Se eri sotto Antiveleno questo effetto dura solo 3 turni 
	- Subisci 1d6 danni 

*Infusione*: +45k, 5 min
Ogni volta che l'avversario colpito da questo veleno cerca di recupare pv in qualsiasi modo, non riesce. 

#### Nuvivolpe


### Pozioni di cura e antidoti

#### Pozione Vitale 
- *Prezzo*: 26-36-68 K
- *Disponibilità*: ?
- *Descrizione*: Classica pozione vitale, da conservare sigillata. Alcune malelingue ritengono che il punto del gdr per Babbei sia comprare un botto di pozioni.  
- *Effetto*: Recuperi 10, 17, 35 pf.

#### Biscotti di Marika
- *Prezzo*: 1d10 K (tirati dal dm, e vale per tutta  la run)
- *Disponibilità*: ?
- *Descrizione*: Una rara ricetta custodita gelosamente. Sono buoni, alla banana con goccie di cioccolat. 
- *Effetto*: Recuperi 1d10 pf.

#### Antiveleno (generico)
- *Rarità*: 2/3
- *Prezzo*: 18k
- *Disponibilità*: 2d4
- *Descrizione*: Un carbone ottenuto bruciando del Salice Bianco in un focolaio di Estia. 
- *Effetto*: Inibisce l'azione di moltli veleni.

#### Vino rosso di Giuda
- *Rarità*: 2/3
- *Prezzo*: 35k
- *Disponibilità*: 1d4
- *Descrizione*: Una bevanda rara la cui uva cresce solo in presenza di Tieflieng che siano vecchi oltre i 100 anni
- *Effetto*: Ogni turno per 3 turni guadagni 2d4 pf. fino al prossimo riposo lungo hai -2 Carisma, -2 Forza, svantaggio a Percepire Intenzioni. 

**NB** Non ha effetto sui Tiefling.

#### Adrilika
- *Rarità*: 2/3
- *Prezzo*: 43k
- *Disponibilità*: 2d4
- *Descrizione*: Ottenibile dal cuore di Viverne, Manticore e Salamandre tiranno.
- *Effetto*: Ottieni 3m  movimento, +2 a Forza, +3 a Destrezza per prove diverse da combattimento, se hai malus a statistiche sono temporaneamente ignorate e ottieni 12 pf per 4 turni (alla fine dei turni perdi tutti i vantaggi compresi i pf). Non recuperi alcun beneficio che normalmente otterresti dal riposo breve oggi. 



#### Acquaforte

- *Rarità*: 1/3
- *Prezzo*: 15k
- *Disponibilità*:
- *Descrizione*: 
- *Effetto*: Se lanciata a un nemico, diminuisce di 1 gli effetti di un armatura

tra le altre cose l'acquaforte grezza è utile per:

- Creare i metalli da forgia
- Le fasi di infusione dei veleni nelle armi 
- La catalizzazioni di numerosi incantesimi

#### Cristalli Naturali

#### Tormentina

- *Rarità*: 1/3
- *Prezzo*: 17k
- *Disponibilità*: 3d8
- *Descrizione*: Radice coltivabile sui monti Congedo dell'Oceano.
- *Effetto*: Il  Filtro è in grado di alterare i principi attivi di molti veleni. 

#### Pasta di Violette

- *Rarità*: 1/3
- *Prezzo*: 20k
- *Disponibilità*: 2d6
- *Descrizione*: fiore dello stelo tossico per la maggior parte degli animali quando è appena raccolto
- *Effetto*: Se assunto con Illantina e ci si concentra su un ricordo per un'ora, dal giorno seguente non si avrà più memoria di quel ricordo.  

#### Adamantina
- *Rarità*: 1/3
- *Prezzo*: 20k
- *Disponibilità*: 3d8
- *Descrizione*: una pozione ottenuta osservando la deita dei Basilischi, esseri dalla grande intelligenza. Purtroppo l'effetto indebolente è legato alla diversità degli organi che la assimilano, e sempre per questo, gli effetti non riescono ad essere permenanenti.
- *Effetto*: +4 intelligenza, per 1 minuto ma subisci 1d8 danni ogni volta che vieni colpito.

#### Fiore di Glicine marmoreo
- *Prezzo*: 24k
- *Disponibilità*: 2d4
- *Descrizione*: Il fiore di glicine sboccia solo in prossimità della magia  dei druidi o in luoghi con grande concentrazione di magia del Ki.
- *Effetto*: ripulisce le vede da traccie di magia o capacità.  Chiunque possa normalmente analizzarla fa  fatica a percepire le tue capacità (CD: 20, senza Vincolo). Se sei un mago però, questo effetto svanisce dopo la prima magia che effettui.

#### Alloro Bianco
- *Prezzo*: 18k
- *Disponibilità*: 3d4
- *Descrizione*: cresce in posti che ricordano una grandissima tristezza nella loro storia
- *Effetto*: un estratto a cui si aggiunge anche una  dose di Mirimar toglie un livello di esaurimento per 1d4 ore.

#### Forensus
- *Rarità*: 2/3
- *Prezzo*: 80k
- *Disponibilità*: 3d6
- *Descrizione*: Estratto dalla sclera degli elfi
- *Effetto*: vedi in bianco e nero con scruvocione e hai +3 a percezione fino al prossimo riposo lungo.

#### Mirimar
- *Rarità*: 2/3
- *Prezzo*: 3k
- *Disponibilità*: 4d8
- *Descrizione*: Una ricetta originale delle storie fittizie del Vanghaal, legata agli alberi delle città elfiche. Trovabile anche in alcuni bar altolocati come euforico leggero.
- *Effetto*: 
	- Bottiglia: Se consumata durante un riposo breve fa guadagnare 2d4 pf. (non stack)
	- Radice: se fumata ha un leggero effetto allucinogeno e rilassante. Ottieni +1 int e Carisma, -1 a Forza e Destrezza 1 un'ora. Hai vantaggio in prove "psichiche" o "da sesto senso" (psicometria, percezione del pericolo, rilevare tesori...)

#### Vino di Yanuar
- *Rarità*: 3/3
- *Prezzo*: 80k
- *Disponibilità*: 1d4
- *Descrizione*: vino della fiabesca città di Yanuar, dalla ricetta segreta. La pianta da cui si estrae è una varietà di uva nota come Vangalina.
- *Effetto*: Guadagni 1d8 pf permanenti.

#### Resintor
- *Rarità*: 3/3
- *Prezzo*: 80k
- *Disponibilità*: 3d6
- *Descrizione*: Un fluido ottenibile dall'ira dei Bruti in cattività, spesso pertanto venduta sottobanco. 
- *Effetto*: non puoi scendere sotto i 2 pf per i prossimi 3 turni (a meno di colpi ceh superino i 60 danni per volta)

