project:
  type: website
  output-dir: docs
  resources: 
   - assets/**
   - imagines/**

website:
  title: "GDR per Babbei"
  favicon: imagines/favicon.png
  sidebar:
    style: "docked"
    search: true
    contents:
     - index.qmd
     - section: "Manuale"
       contents:
        - capitoli/Regole/Regole.qmd
        - capitoli/Regole/Classe combattente.qmd
        - capitoli/Regole/Classe Mago di Merlino.qmd
        - capitoli/Regole/Regole Biblioteca.qmd
     - section: "Mercato"
       contents: 
        - capitoli/Mercato/veleni.qmd
     - section: "Lore" 
       contents: 
        - capitoli/Lore/Cultura generale.qmd
     - section: "Utilities"
       contents: 
        - capitoli/Utilities/regole fight rapide.qmd
     - capitoli/credits.qmd
      
  navbar:
    right:
      - text: "Scarica scheda PG"
        icon: file-arrow-down
        href: pdf/scheda.pdf
      - text: "Sei un DM?"
        href: "javascript:showDMModal()"


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true
    include-in-header: assets/include-head.html
    include-after-body: 
      - assets/dm-modal.html
      - assets/scripts.html
      - assets/footer.html
      - assets/swipe.js
    css: 
      - /assets/title_style.css
      - /assets/navbar_style.css
  

language:
  toc-title: "Indice"