project:
  type: website
  output-dir: docs
  resources: 
   - assets/**

website:
  title: "GDR per Babbei"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - Regole.qmd
      - Classe combattente.qmd
      - Classe Mago di Merlino.qmd
      - Regole Biblioteca.qmd
      
  navbar:
    right:
      - text: "Sei un DM?"
        href: "javascript:showDMModal()"

format:
  html:
    theme: cosmo
    toc: true
    include-in-header: assets/include-head.html
    include-after-body: 
      - assets/dm-modal.html
      - assets/scripts.html