project:
  type: website
  output-dir: docs
  resources: 
   - assets/**
   - imagines/**

website:
  title: "GDR per Babbei"
  favicon: imagines/favicon.png
  sidebar:
    style: "docked"
    search: true
    contents:
     - index.qmd
     - section: "Manuale"
       contents:
        - href: capitoli/Regole/regolamento.qmd
          text: "Regole generiche"
        - href: capitoli/Regole/creazione.qmd
          text: "Costruzione del Personaggio"
        - href: capitoli/Regole/spiegone.qmd
          text: "Lo Spiegone"
     - section: "Mercato"
       contents: 
        - href: capitoli/Mercato/generale.qmd
          text: "Mercato Generico"
        - href: capitoli/Mercato/veleni.qmd
          text: "Erboristeria"
        - href: capitoli/Mercato/armeria.qmd
          text: "Fabbro e Armaiolo"
        - href: capitoli/Mercato/collezionista.qmd
          text: "Il Collezionista"
     - section: "Lore di Irradan" 
       contents: 
        - href: capitoli/Lore/lore.qmd
          text: "Lore Generale"
        - section: "Approfondimenti"
          contents:
          - href: capitoli/Lore/Approfondimenti/città.qmd
            text: "Città"
          - href: capitoli/Lore/Approfondimenti/foreste.qmd
            text: "Foreste"
          - href: capitoli/Lore/Approfondimenti/storia.qmd
            text: "Storia"
          - href: capitoli/Lore/Approfondimenti/dèi.qmd
            text: "Dèi"
          - href: capitoli/Lore/Approfondimenti/magia.qmd
            text: "Magia"
     - section: "Utilities"
       contents: 
        - capitoli/Utilities/regole fight rapide.qmd
     - capitoli/credits.qmd
      
  navbar:
    right:
      - text: "Scarica scheda PG"
        icon: file-arrow-down
        href: pdf/scheda.pdf
      - text: "Sei un DM?"
        href: "javascript:showDMModal()"


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true
    include-in-header: assets/include-head.html
    include-after-body: 
      - assets/dm-modal.html
      - assets/dm-unlock.html
      - assets/scripts.html
      - assets/footer.html
      - assets/scripts_loader.html
      - assets/swipe.html
    css: 
      - assets/title_style.css
      - assets/navbar_style.css
  

language:
  toc-title: "Indice"