project:
  type: website
  output-dir: docs

website:
  title: "GDR per Babbei"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - Regole.qmd
      - Classe combattente.qmd

format:
  html:
    theme: cosmo
    toc: true
    include-in-header: include-head.html