---
title: "Benvenuto, Giocatore"
format:
  html:
    theme: default
---

## Orientarsi nel Gioco

La voce "Manuale" ha le regole principali del gioco. 
La voce "Mercato" enlista una serie di shop che potete trovare quasi in tutte le ambientazioni
La voce "Lore di Irridan" presenta la lore di base del gioco.

Non tutte le regole e tutta la lore è direttamente navigabile, per rednere più semplice il sito. Se sapete di qualcosa però, potete cercarlo direttamente dall'icona grande della lente. Inoltre, se vagate nel sito potete scoprire cose nuove. Alcune classi, razze, poteri e via discorrendo sono infatti disponibili solo su richiesta se voi li trovate.

### Come cazzo si chiamava il file quello con le regole? 

[Eccolo](/capitoli/Regole/creazione.html)

### Bellissimo Ema ma come mi oriento? 

- La cartella "**Lore**" risponde alle tue domande sull'ambientazione, ci sono 5 files di approfondimento. Le altre 3000 pagine del sito non sono elencate, ma si raggiungono leggendo la lore, perché la struttura è a imbuto.  Se trovate una pagina un po' imboascata che vi interessa vi consiglio di salvarvi il link da qualche parte.

- La cartella "**Mercato**" contiene i punti di interesse che potete realisticamente trovare in quasi tutte le città. I prezzi e tutte le informazioni sono comunque rimessi  all'ultima parola del DM (mica che qualcuno pensi che una volta scritto su un sito statico in qmd abbia un significato esagerato.)

- Il file [regole](/capitoli/Regole/regolamento.html) risponde alle domande tecniche sulle regole in generale. 

Tenete a mente che molte parti sono ancora in costruzione. A brevissimo dovrebbe arrivare l'aggiornamento più significativo cioè quello dei veleni. 

### Suggerimenti 

Siete invitati a mandarmi suggerimenti, proposte di lore, segnalazioni di errori e compagnia, proposte  di oggetti che vi interesserebbe creare, etc, alla casella di posta che si apre infondo alle pagine.


### Diffusione 

Per ora non fate girare il sito. Per una decina di ragioni diverse. Perché non è pronto, perché non ho deciso cosa ce ne faremo, per ragioni di sicurezza (è hostato su ghithub, ma il codice sorgente è sempre a un click di distanza. E ci sono dei javascript qua dentro). E poi c'è un indirizzo email, che non è il massimo. 

## Filosofia di Gioco

Se avete già giocato con me, skippate pure.

### Gioco di ruolo?

Se per caso qualcuno non avesse mai giocato di ruolo, ecco a voi lo [spiegone](/capitoli/Regole/spiegone.html)

### Cosa posso giocare? 

Tutto. O quasi. Puoi combinare le abilità  disponibli, o scegliere tra le numerosissime classi nascoste. Ho pensato a tantissime cose, c'è una lore sufficientemente vasta per accogliere quasi qualsiasi tipo di immaginario di "fanatasy" che si muova fino a un accenno di steampunk (se il temrine vi comunica qualcosa.) Puoi anche chiedermi una classe nuova, un potere nuovo, ne discutiamo assieme e vediamo di trovare un modo viabile per farlo. 

### Ma i Livelli? Presentazione del gioco

A Ema i livelli non sono mai piaciuti. Nel DND classico, il contesto di gioc è "Siete degli avventurieri che hanno bisogno di soldi (pretesto per menare le mani molto battuto, solida alternativa a "cerco vendetta") quindi andate nei dungeon, menate i mostri, e livellate e diventate più forti". Questo contesto narrativo non mi piace, e non mi piace rendervi più forti perché sì. 

Io propongo un gioco in cui il vostro obbiettivo sia Dominare l'Ambientazione. Tipicamente ci sarà una qualche questione, legata sicuramente al background del vostro personaggio che vi darà motivo di menare le mani dove ce n'è bisogno, affinché voi possiate risolvere quel problema. Tipicamente per risolverloi vi sarà necessario (o facilitante)  esplorare la lore, l'ambientazione che ho così (ossessivamente) preparato per e con voi. Diventerete forti quindi in un contesto preciso che riguarda il mondo che abbiamo creato assieme e la storia del vostro persoanggio. 

Sia messo in chiaro che questo stile di gioco potrebbe anche non piacervi. In DND è quasi mandatorio una fight per sessione, o poco vicino. Qui no. Il fight c'è, se serve, se ve lo andate a cercare, ma si può anche schivare. C'è sempre un modo alternativo per superare i conflitti. 

Per riassumere il mio gioco "L'ambientazione che ho creato procederà in una direzione o l'altra a seconda di come la influenzate voi. Finché vi muovete nei contorni della mia ambientazione, potete agire come volete. "

### Si,si, bello, quindi come si diventa forti? 

Ci sono una serie  di modi:

- Narrativa: il DM può accordare un ruolo forte, un esercito, un che cazzo ne so, a seconda di come giocate, di cosa scegliete di fare 
- Negozi: non sottovalutate tutto quello che può essere reperito nelle sezione mercato. Una manciata di pozioni può rendervi molto forte, specie se le infondete nelle armi. Oppure potete andare a fare incantare le armi. Questi sono i metodi pigri, e comunque giocatori molto raffinati riusciranno a rompere il gioco anche solo con queste meccaniche. 
- Power-up: ci sono molti tipi di power up che potete trovare quà e là nel gioco, o che potete  andarvi anche a cercare 
  - Item: oggetti, armi e affini che vi rendano più forti 
  - Abilità: potete sbloccare numerose abilità nel gioco
  - Patti: potete creare patti con numerose entità (es: la dea Indra)
  - Ricerca e sviluppo: andando per biblioteche, chiedendo a NPC di insegnarvi una capacità, esplorare la lore. Tutte modaliità che se ben gestite vi consentono di ottenere un power-up. 

In generale più ci mettete del vostro più io facilmente vi seguirò. Non abbiate paura di chiedere e sperimentare. Potete anche propormi classi di gioco ex-novo. Tipicamente la mia risposta sarà un "possiamo provarci". 

Ho avuto PG in grado di diventare forti facendo 20 nat al momento giusto, altri facendo improbabili patti con le Sirene, altri solo fregandomoi adeguatamente con i potenziamenti, altri sottomettendosi a una divinità.

## Ma questo sito è sicuro? 

Lo scrivo solo perché qualcuno dei miei giocatori è un po' paranoico ed è riuscito a farmi questa domanda:

- Questo è un sito statico
- Ci sono solo due file js e li ho scritti interamente con le mie manine d'oro (sbatta)
- HTTPS 
- Hostato su Github 
- Ogni push request deve essere approvata in due passaggi (sbatta)

Per essere un sito con le regole di un gdr e basta, è fin troppo sicuro. 