---
title: "Lore-Cultura Generale"
format:
  html:
    theme: default
---

Per descrivere il mondo di Irradan, ci lasciamo accompagnare dalla voce di Locandiere.jpg, che ci offre una rapida panoramica del mondo com'è. Il locandiere sarà probabilmente un umano, perché più numerosi dei nani, che sono comounque ben sparpagliati un po' dovunque.

## Il Mondo di Irradan

**Instabile**: Irradan è un mondo che continua a cambiare, dove disgrazie e cataclismi si abbattono in continuazione sulle città. Non c'è stabilità: un uomo è abiutuato a non sapere cosa si trovi nella città affianco alla propria. O almeno, figliolo, 10 anni fa ci sono stato, ma non puoi mai sapere se nel frattempo le cose siano cambiate o meno. Non puoi sapere se per esempio la città non sia stata distrutta.

    - Le strade: viaggiare in generale è già pericoloso, un po' sconsigliato. Si viaggia solo su sentieri, strade sicure. Mai avventurarsi nelle [foreste](/capitoli/Lore/Approfondimenti/Foreste.html) senza consocere le strade sicure. Muoversi altrimenti è una cosa che si fa a proprio alto rischio e pericolo. I mercanti ottengono per questo la loro fortuna, sono loro che portano avanti la fragile economia del mondo. E i naviganti, ancora di più.

**Le Città e Regioni** : La forma del mondo non è ben nota. Abbiamo uan vaga idea di quali siano le [regioni](/capitoli/Lore/Approfondimenti/Citt%C3%A0.html) più importanti, se non altro di fama. Ma non sappiamo di sicuro se siano ancora come ce le hanno raccontate qualche anno fa. 

Sono poche le città che mantengono una identità più che centenaria. Anch'esse sono soggette a cambiamento, ma se si entra in una città, e quella città ha un Re o Regina, allora si può stare abbastanza certi che quel titolo gli viene riconsociuto solo perché è potente. Perché se lo merita. E quella città si sa difgendere dal mondo.

**Le razze** allora figliolo, te la faccio semplice

- I nani sono dalla nostra parte. Ci aiutano, sono anche abili mercanti, spesso e volentieri. Alcuni pensano che alcuni siano un po' risentiti verso gli umani, che si credano migliori di noi. Ma io non credo proprio, sono gente per bene. 
- Gli elfi, no. Non ti fidare. Sono molto, molto pericolosi, psicopatici eremiti delle montagne. Selvaggi be vestiti. Stuprano le nostre donne, attaccano le nostre città, quando decidono che sconfinano nei loro territori. E c'è anche poco che si possa fare contro di loro. Se ne vedi uno stai all'occhio. Uno da solo sarà probabilmente civilizzato, ma non c'è comunque da fidarsi. 
- Mezzelfi: Diversa storia è se ne vedi uno ibrido. Li riconosci, non so come dire... sono meno selvaggi. Sono più come noi, molto molto longevi, ma come noi, e forse anche un po' sfortunati, probabilmetne la loro madre è stata vittima di uno stupro. 
- Dragonide: sono strani, senza dubbio. Dicono che diventino dei draghi, ma io non ci credo, è una semplice diceria, sono persone come noi, io ci ho parlato. Certo, stai alla larga perché starnutiscono fiamme, ma non c'è bisogno di prendere contromisure.
- Orchi: barbari forse superiori agli elfi, ma è più comune trovarne qualcuno di civilizzato. Stai comunque all'occhio.
- Diavoli: li riconosci subito, con le corna e la coda, e la pelle lucida di un colore scuro. Fidati poco, sono malvagi e corrotti. Nessuno ha buona memoria della loro razza. 

### I Ruoli da Rispettare

In questo ordine di importanza si susseguono quelli che per la persona comune sono i Potenti del mondo. O tutte quelle persone per cui si porta un certo tipo di rispetto.

-   Chierico: i rappresentanti degli [dèi](/capitoli/Lore/Approfondimenti/D%C3%A8i.html) su questa terra. Non sono solo preti, quasi profeti. Un chierico potrebbe trattenere da solo il potere necessario per eradicare una città. Alcuni chierici addirittura di riuniscono sotto degli ordini. Alcuni notabili sono i chierici di Mondul, dio della morte, i chierici di Estia.

    -   *Rispetto*: una volta che egli si dimostra tale, viene portata riverenza asssoluta.

-   Mago: i potenti esecutori della [magia](/capitoli/Lore/Approfondimenti/magia.html). Sono figure non comuni, eccentriche, ma soprattutto pericolose. Ad ogni buon abitante di Irradan viene insegnato che i maghi bisogna lasciarli stare: "tu fatti gli affari tuoi, e probabilmente quello sarà così perso tra le sue... bizzarrerie, che ti lascerà in pace". E non è così inesatto. Alcuni maghi possono anche farsi pagare come mercenari.

    -   *Rispetto*: se si sospetta fondatamente che sia un mago, si usa la massima cautela, nonostante non gli si debba niente.

-   *Alfiere*: un combattente che supera tutti i combattenti in una regione, o in una... "cosa". Esiste l'alfiere dei Bardi, ho sentito, ad esempio. O l'alfiere dei Marinai. Insomma un difensore della memoria di quella cosa o regione. Si battono per evitare la dispersione della memoria. Che spesso significa che si battono per evitare che venga distutto il villaggio. Ottimo no?

    -   *Rispetto*: una volta che mostra il Drappo santo, allora c'è da stare tranquillli. Gente valorosa, gente per bene. E gente a cui mostrare un grande rispetto. Tipicamente non hanno bisogno di niente, ma è buona cortesia offrire loro aiuto.

-   *De Cervantes:* un cavaliere che appartiene alla famiglia De Cervantes si chiama GranCavaliere. I Gran cavalieri agiscono sulla base di un Codice di Cavalleria, quindi saranno senza dubbio gente a modo.

    -   *Rispetto*: dei De Cervantes ci si può fidare, brava gente. Sempre il caso di mostrare cortesia, e riconoscenza. Ma i De Cervantes sono una famiglia ricca, non hanno tipicamente bisogno di niente.

-   *Erboristi*: ogni villaggio che può vantare uno speziale ha un vantaggio rispetto agli altri. Sa difendersi meglio, è più frequentato da guerrieri nobili, le figure magiche che lo frequentano tendono a essere meno prepotenti e più rispettose, e ha possibilità di passare indenne epidemie, pestilenze, e così via. Sono eccentrici quasi come un mago, ma salvano vite, curano i nostri figli.

    -   *Rispetto:* una volta che li conosci, è il caso di trattarli con lo stesso rispetto degli altri del villaggio.

-   *Bibliotecario:* le poche e rare biblioteche in un villaggio fanno fiorire la poca economia, dirigono qui i commerci... avendo una biblioteca siamo considerati preziosi, e quindi da difendere. Più che gestire i libri un bibliotecario non fa, ma è già abbastanza. Grazie alle biblioteche, è possibile risalire almeno a quel poco della nostra [storia](/capitoli/Lore/Approfondimenti/Storia.html). Ma fidati ragazzo mio, è tempo sprecato.

    -   *Rispetto*: un cenno del capo, ragazzo. Non serve che pensi bene di noi, ma non vorrei mai che pensasse male.

-   *Venator*: chi difende il nostro mondo dalle calamità del mondo sono questi Cacciatori. Sono tipicamente violenti, senza scrupoli, ossessionati da questa cosa della caccia. E a buon guaadagno, certo: difendono da ogni maggiore pericolo: i vampiri, le bestie Selvagge, i Draghi, e i temutissimi demoni....

    -   *Rispetto:* ogni locanda deve loro un vitto e alloggio. Della qualità più economica, ma glielo deve, finché sta risolvendo un problema nella nostra città. E una volta che è abbastanza chiaro che non si tratti di un semplice cacciatore, ma di un vero Venator, allora... sì, piorta rispetto, ragazzo.

-   *Bardi*: chi veramente ci consegna le memorie del mondo, figliolo, sono i cantastorie, i trovatori. Si dice che vaghino da un popolo all'altro, addirittura raggiungono si dice i popoli che mantengono una memoria, per un motivo o per l'altro, e connettono le conoscienze. Buon costume è dargli qualche moneta quando parlano, quando raccontano. Non sai mai cosa possa essere falso cosa possa essere vero, ma qualcosa di vero c'è. 

    -   *Rispetto:* non gli dobbiamo niente, ma è meglio tenercelo buono, può essere utile sapere se si avvicina una disgrazia, o che fine abbiano fatto le genti dei paesi vicini. Meglio essere cauti, alcuni di loro ne sanno di magia. Che non è mai una buona cosa...

-   *De Clairein:* I de Clairein sono una famiglia molto ricca, dall'origine e collocazione sconsciuta. Hanno validissimi contatti e conoscenze tra emrcanti, ladri, assassini e naviganti. Sono loro il segnale implicito che spesso una città è degna di nota. Sono loro che arrivano quando in una città ci sono Bibliotecari, Erboristi e così via. Potrebbero anche sapere notizie dal mondo, quindi meglio ingraziarseli.

    -   *Rispetto*: figliolo fa' quello che vuoi, ma non farteli nemici. In realtà è difficile scoprire che una persona sia un Clairein, per cui per non sbaglaire puoi trattare con rispetto i mercanti in Generale.

-   *Naviganti*: pirati, marinai e naviganti in generale sono quelli che possono fare prendere il volo all'econocmia di un paese. 

    -   *Rispetto:* meglio trattarli come generici mercanti, con un sottofondo di rispetto e onestà. Potrebbero anche loro sapere notizie dal mondo, quindi meglio ingraziarseli. Inoltre alcuni di loro potrebbe portare qualche stranezza.