---
title: "Regole e meccaniche"
format:
  html:
    theme: default
---

### Regole generali, le Prove

- Prova di Combattimento: una prova di combatteimento consiste in 
	- Un attaccante che effettua un tiro per colpire su Destrezza
	- Un difensore che effettua un tiro per difendere su Destrezza
    - NB: se attacchi un nemico disarmato (o che non ha colpo senz'armi), il risultato complessivo >11 viene considerato un critico. 

- Prove di Abilità: tutti i giocatori possono eseguire le prove di Abilità usando i proprio modificatori 
  - Prove di Abilità Speciali: queste prove sono abilità non riproducibili dalle persone normalmente senza un training specifico. Molto sta al master decidere se o meno lasciare eseguire tentativi disperati. Per esempio, è facile concedere a una persona che non ne sa nulla, comunque provare un tiro di Medicina, anche se rischia di fare più danno che altro, mentre è un po' meno credibile pensare di improvissare "Percezione del magico" o "Scassinare" senza saperlo fare.

- Prove di Carisma: in generale chiamiamo  prova di Carisma il provare a fare una faccia carina, a dare una buona impressione. 
  - Prove di Inganno e Persuasione: 
    - Quando un pg dice una bugia a un npc o pg, deve tirare di Carisma per Ingannare.
      - Quando un pg sospetta che un pg o npc gli stia mentendo, deve tirare Intelligenza contrapposta ad un tiro  di Carisma dell'avversario
    - Quando un pg cerca di convincere un npc, deve tirare di Carisma per Persuadere. 
      - Se il pg cerca di spaventare, mettere pressione, o alle strette, allora si usa l'abilità spaventare. 
      - Un DM può fare rispondere un NPC con intelligenza a una prova di persuasione al posto che usare una CD.

#### Meccaniche di supporto alle prove

- Vantaggio: la meccanica per cui tiri contemporaneamente due dadi e tieni il risultato più alto
- Svantaggio: la meccanica per cui tiri contemporaneamente due dadi e tieni il risultato più basso
- Ispirazione: il DM può darti una ispirazione se ritiene che tu abbia effettuato in modo  particolarmente brillante o riilevante un aspetto del gioco. Puoi consumare una ispirazione in qualsiasi momento per iritrare un qualsiasi dado a tuo piacere, prima di consocere le conseguenze del primo  risultato. Devi però usare il nuovo risultato.  

### Regole generali, i pf

- PF: ottenete di norma indietro tutti i vostri PF con un riposo Lungo, e nessuno con un riposo Breve. 
- Inoltre i vostri PF possono salire oltre il massimo utilizzando pozioni o altre abilità, e rimangono oltre il massimo fino alla fine della giornata. 
  - Se la pozione o l'effetto specificava, pf permanenti, si alzano in modo indefinito, al vostro prossimo riposo lungo andate al nuovo max. 

### Regole generali, la morte 

- Se arrivate a 0 pf, tu e il DM vi scontrate in un epico duello contro la morte: ogni turno entrambi tirate un d20. Chi vince segna una vittoria. Il primo che arriva a tre vittorie vince. Se il DM arriva a 3, sei morto. Se ci arrivi prima tu, torni a 1pf, privo di sensi.
- Se arrivi direttamente sotto i -15 pf, sei morto senza tirare. 

### Regole di Fight

Durante il combattimento si divide 1 minuto di combattimento in 10 rounds.
Durante un round tutti i giocatori ed NPC hanno un turno. 

I turni si susseguono uno dopo l'altro, poi ricominciano. 
Il primo a giocare un round è il giocatore con iniziativa più alta. Il dm può comunque decidere un'altra successione per motivi magari legati alla situazione contingente. 

Durante ogni turno si ha a disposizione le seguenti possibilità, non necessariamente in quest'ordine.

- **Un'Azione**: che può essere alternativamente 
	- Un attacco con arma
	- Una delle capacità concesse dal sistema 
	- Una prova di Abilità
	- Un'altra azione che il pg intende eseguire, da discutere col DM
	
- **Un'Azione Bonus**: che può essere spesa per
	- Consumare una pozione 
	- Eseguire una capacità di quelle concesse dal regolamento
	
- **Movimento**: il movimento è di default per tutti di 9 metri. Il movimento può essere diviso in più parti nello stesso turno.

**Ingaggio**: Se si entra in fight all'arma non a distanza, attaccando o venendo attaccati, si è considerati *ingaggiati*. Durante l'ingaggio non è possibile staccarsi dal combattimento a meno che 

- L'avversario non finisca a terra
- L'avversario non perda conoscenza
- Non si spenda una azione per *Disingaggiare*

- Se ci si sposta da un ingaggio, si è soggetti a *Attacco di opportunità*. Cioè l'avversario può tentare di colpirti per il fatto che ti sei mosso. 

Ovviamente, questa meccanica vale anche al contrario, cioè hai a disposizione attacco di opportunità se l'avversario scappa senza disingaggiare.

**Fiancheggio**
Quando colpisci un avversario ingaggiato ottieni Vantaggio al tiro per colpire.

**Reazione**
Durante il turno degli avversari non potete fare niente, a meno che non utilizziate una reazione. Ne avete una a fight a testa come minimo. 

- Reazioni: Con la reazione puoi 
	- Utilizzare le manovre che consentono l’uso in reazione.
	- Darsi vantaggio a un tiro di attacco di opportunità o contrattacco.
	- Qualsiasi cosa non sia utilizzare un’abilità, attaccare, o usare pozioni, da discutere con il DM.  

**Critici**

- Se si fa 20 nat a Difendere, il tiro vince automaticamente. Inoltre si ottiene *contrattacco*, cioè è possibile provare a colpire nel turno dell'avversario. (è possibile darsi vantaggio con una reazione)
- Se si fa 20 nat a Colpire, il tiro infligge il doppio dei danni, e può essere parato solo da 20 nat 
- Se si fa 1 nat a Colpire, il tiro perde automaticamente. Non ci sono conseguenze aggiuntive, a meno che il DM non lo ritenga opportuno. 
- Se si fa 1 nat a Difendere, il tiro perde, a meno che il nemico non faccia 1 a colpire. Inoltre, subisci il doppio dei danni che subiresti. (Se si risponde con 1 nat in difesa a un 20 nat in attacco, sì, i danni vengono moltiplicati per 4. Mi dispiace.)

*NB* Concatenazione di critici: se a un contrattacco si risponde con un 20 nat, si va avanti in una catena di contrattacchi continui finché uno dei due perde. 

*NB* se delle combo o effetti fanno crittare i critici più volte, non c'è limite al numero di volte in cui si raddoppia i critici. Ma si usano gli stack: raddoppiare un critico raddoppiato significa danno x6, non danno x8.

#### Condizioni e note particolari 

- Hai vantaggio a colpire un nemico a terra con arma in mischia, a distanza non cambia niente
- Se si è coperti in qualche modo dagli attacchi a distanza è possibile  ottenere vantaggio a schivare (per esempio sei tatticamente combattendo dietro a un albero)
- Alzarti in piedi in fight costa metà del tuo movimento 

### Regole per tiri di Conoscenza

Se volete sapere una cosa su un argomento vi viene detto dal DM di tirare come al solito. A seconda di cosa viene chiesto e come viene formulata la domanda, il tiro può essere su Storia, o su Accademia, o un'altra delle 5. A seconda del risultato 

- Fallimento: cazzi vostri, vi saranno dati accenni di informazioni già note a tutti
- Successo basso: vi verranno dette alcune cose che non sapevate già
- Successo alto: avete diritto a una introduzione dell'argomento, poi potete fare delle domande pari al vostro  modificatore sull'argomento. Se avete +2 a Natura potette  farmi 2 domande nella direzione che vi pare a voi su questo argomento. 

### Regole Biblioteca Generico

Se avete conoscenze ssu un argomento ma volete approfondirle, e siete in unna città che ha una bibliteca potete fare una ricerca.

Ogni volta che entrate dichiarate quanto del tempo che volete spendere spendete nella biblioteca. E poi ognuno di voi dice quanto tempo passa in ogni sezione. Tipicamente una biblitoeca offre 2 slot tempo gratuito a persona al giorno (cioè due ricerche)

Gli slot tempo vengono usati per rispondere a una _Domanda_. Con Domanda intendo che voi non potete passare chiaramente 4 giorni a leggere un tomo di 600 pagine, ovviamente voi dovete cercare di formulare una domanda riguardo a un'informazione. Se non avete idee andate dal bibliotecario di turno.
A seconda di come viene formulata la domanda, essa sarà una domanda che richiederà competenze di Conoscere diverse. Verrete indirizzati a una sezione diversa della biblioteca. 

Un argomento può essere esplorato in modi diversi a seconda dell'approccio. La domanda su "Excalibur" può essere formulata per sapere qualcosa sulle leggende (Folklore), sulle imprese commpiute con essa (Storia), su come è stata forgiata (Accademiche), e così via. SI otterrano risposte diverse a seconda della domanda, e le vostre domande sono limitate. 

Ricercare informazioni per una Conoscenza per la quale si ha 0 (o meno) comporta Svantaggio. 

Tirate  applicando  i vostri modificatori:

- Fallimento critico: informazioni sbagliate
- Fallimento: non trovate granché 
- Successo basso: qualche accenno di informazione 
- Successo medio: buone informazioni 
- Successo pieno:  informazioni molto complete 
- Critico: non c'è nessun critico nelle biblioteche

Le informazioni che otterrete saranno relative soltanto alla sezione in cui siete. 

#### Regole Biblioteca Dettagliate 

Regole: ogni volta che entrate dichiarate quanto del tempo che volete spendere spendete nella biblioteca. E poi ognuno di voi dice quanto tempo passa in ogni sezione.

Gli slot tempo vengono usati per rispondere a una _Domanda_. Con Domanda intendo che voi non potete passare chiaramente 4 giorni a leggere un tomo di 600 pagine, ovviamente voi dovete cercare di formulare una domanda riguardo a una informazione. Se non avete idee andate dal bibliotecario di turno.

Ricercare informazioni per una Conoscenza per la quale si ha 0 (o negativo) comporta Svantaggio. 

Voi  tirate  applicando  i vostri modificatori e potete fare 
- Fallimento critico: informazioni sbagliate
- Fallimento: non trovate granché 
- Successo basso: qualche accenno di informazione 
- Successo medio: buone informazioni 
- Successo pieno:  informazioni molto complete 
- Critico: non c'è nessun critico nelle biblioteche
Le informazioni che otterrete saranno relative soltanto alla sezione in cui siete. 

###### **1. Conoscenza: Storia**

Questa sezione si occupa dei racconti del passato, delle cronache delle civiltà e delle guerre antiche. Si può dividere ulteriormente in:

- **Cronache dei Regni**: Contiene registri e diari di regnanti e nobili, storie di imperi e dinastie. Qui si trovano genealogie, alleanze e trattati.
  - **Complicazione**: Molti testi sono deteriorati o frammentati, richiedendo tempo per decifrarli.

- **Personaggi Storici Rilevanti**: Questa sezione contiene resoconti di battaglie storiche, strategie militari e piani di guerra. Gli eroi di guerra sono raccontati nei minimi dettagli.
  - **Complicazione**: Alcuni resoconti potrebbero essere troppo glorificati o esagerati, distorcendo i fatti.

- **Civiltà Perdute**: Una raccolta di testi rari e misteriosi che raccontano di civiltà scomparse e antichi regni. Qui si trovano leggende e resoconti di imperi che sono ormai polvere.
  - **Complicazione**: Molti testi sono scritti in lingue antiche o dialetti dimenticati, richiedendo tempo per la traduzione, e soprattutto  richiedendo le lingue apposite.

- **Cronache dei De Cervantes**: Una raccolta di testi della famiglia De Cervantes, o informazioni specifiche. Inoltre sono esperti di Numismatica.
  - **Complicazione**: Molti si firmano De Cervantes per dare credibilità ai loro testi, un viaggio nella Sezione Accademiche può aiutare. Nota, alcune volte possono esserci delle guide passo passo per imparare manovre, o modalità per spostare manovre da un'arma all'altra, e possono essere appositamente cercate (è necessario avere competenza almeno in un arma)


###### **2. Conoscenza: Natura**

Questa sezione tratta di tutto ciò che riguarda il mondo naturale, dalle creature alle piante, dai climi ai fenomeni naturali. Sottosezioni potrebbero includere:

- **Erbario degli Antichi Botanici**: Qui sono catalogate piante rare e comuni, con descrizioni dei loro effetti curativi o tossici. Contiene testi di erboristi celebri.
  - **Complicazione**: Alcune pagine sono illeggibili o rovinate da muffa o licheni, richiedendo uno sforzo aggiuntivo per la consultazione.

- **Bestiario delle Creature Selvagge**: Una collezione di testi sulle bestie del mondo naturale, dalle più comuni alle creature mitologiche. Comprende descrizioni di habitat, comportamenti e caratteristiche fisiche.
  - **Complicazione**: Alcuni volumi contengono solo disegni incompleti o appunti frammentari, rendendo difficoltosa la comprensione.

- **Bestiario delle Bestie Marine**: Una collezione di testi sulle bestie del mondo naturale, dalle più comuni alle creature mitologiche. Comprende descrizioni di habitat, comportamenti e caratteristiche fisiche.
  - **Complicazione**: Alcuni volumi contengono solo disegni incompleti o appunti frammentari, rendendo difficoltosa la comprensione.

- **Bestiario Dei Venatores** Contiene informazioni più approfondite su Vampiri, Draghi, Tiefling antichi. Sulle Tecniche di Caccia e di artigianato dell'Ordine e sui  suoi membri.
  - **Complicazione**: Alcuni volumi sonno chiusi da sigilli incantati, che richiedono o una forzatura magica da parte di un Bardo o di un Mago, o l'apertura da parte di un Venator. 

- **Fenomeni Naturali e Catastrofi**: Questa sezione copre tutto ciò che riguarda gli eventi climatici e geologici, come terremoti, tempeste e vulcani. Include anche resoconti di disastri naturali del passato.
  - **Complicazione**: I testi sono a volte troppo tecnici o basati su teorie ormai superate, rendendo difficile separare il mito dalla realtà.

###### **3. Conoscenza: Folklore**

In questa sezione si trovano storie popolari, leggende e racconti tramandati oralmente. È una sezione più caotica, ma ricca di informazioni sulla cultura popolare e i miti.

- **Racconti delle Creature Mitologiche**: Una raccolta di leggende e miti su creature fantastiche: draghi, fate, licantropi e simili. Spesso i testi sono mescolati con superstizioni locali.
  - **Complicazione**: Molte leggende sono contraddittorie, rendendo difficile determinare la verità.

- **Storie di Eroi Popolari**: Narrazioni di eroi locali, fuorilegge o guerrieri leggendari, spesso esaltate da canti e poemi. Qui si trovano le storie di come questi eroi abbiano sconfitto mostri o superato sfide impossibili.
  - **Complicazione**: Gli eroi popolari sono spesso idealizzati, e i fatti reali possono essere distorti dalle interpretazioni successive.

- **Fiabe e Racconti per Bambini**: Questa è una sezione in apparenza leggera, ma a volte le fiabe contengono insegnamenti nascosti o riferimenti ad antichi poteri. Spesso le streghe e gli spiriti maligni sono metafore per forze oscure.
  - **Complicazione**: Le fiabe sono volutamente vaghe o simboliche, richiedendo interpretazione.

- **strumenti e ninnoli**

###### **4. Conoscenza: Religione**

In questa sezione si trovano i testi sacri, le scritture e le storie dei culti e delle divinità. Molte opere sono venerate o proibite.

- **Sacre Scritture delle Religioni Maggiori**: Testi sacri e scritture delle divinità principali, completi di interpretazioni di chierici e profeti. Qui si trovano antiche profezie e regole divine.
  - **Complicazione**: Alcuni testi potrebbero essere considerati eretici o distorti da riformatori passati.

- **Culto degli Dei Oscuri**: Libri proibiti che trattano dei culti oscuri e delle divinità malvagie. Questi testi contengono rituali e invocazioni, spesso incompleti o criptici.
  - **Complicazione**: La lettura di questi testi potrebbe avere effetti negativi, come visioni o maledizioni.

- **Reliquie, Idoli e Santi**: Testi che trattano delle reliquie sacre e delle vite dei santi, con dettagli sui miracoli compiuti e le reliquie sacre ancora esistenti (un esempio su Tutti il Drago Bianco).
  - **Complicazione**: Alcuni resoconti sui santi sono leggende, e separare il mito dalla verità può richiedere sforzo, un viaggio alla sezione Accademia può aiutare. 

- **Guerre degli Angeli e Angeli Custodi**: Testi riguardo alle complicate guerre degli Angeli, gli Angeli custodi
  - **Complicazione**: Alcuni manuali potrebbero offrire indizi su come trovare degli angeli custodi. Non è detto che scoprire di averne uno sia  una cosa buona.

###### **5. Conoscenza: Accademia**

Questa sezione contiene testi scientifici, filosofici e tecnologici.

**Filosofie e Teoria della Conoscenza**: Libri che esplorano le grandi domande dell’esistenza, le etiche della magia e della scienza, le varie idee e filosofie di svariati popoli. Qui si trovano trattati di filosofi e pensatori. Si può usare questa sezione per provare a cogliere delle incoerenze tra pensatori e capire  chi ha ragione quando gli autori sono confusi o contradditori.

**Astronomia**: Catalogo delle Stelle, della loro posizione e come interpretarla. Se si ha almeno 2 a Accademia dopo aver speso almeno 2 slot dentro questa sezione, si ottiene una Percezione del Pericolo durante la Notte Successiva. 

**Alchimia e Scienze Naturali**: Una raccolta di testi sugli elementi, la trasmutazione della materia e la creazione di pozioni e sostanze magiche.
  - **Complicazione**: Molti esperimenti sono pericolosi o mal documentati, il che può portare a errori.

**Invenzioni e Scoperte**: Un luogo che raccoglie trattati sulle più grandi scoperte e invenzioni della storia. Qui si trovano i progetti originali di macchine antiche, armi e meraviglie architettoniche. Ricostruire come certe invenzioni abbiano cambiato il mondo.
- **Complicazione**: Alcuni progetti sono troppo complessi per essere compresi senza ulteriori ricerche. Se si possiede Ingegneria, si ottiene vantaggio a questo tiro.

**Arte del Conio e Contraffazione**: questa sezione tratta la Numismatica contemporanea, dopo l'invenzione del Kilia, che è comunque possibile contraffarre. Un Nano o un Ignegnere possono acquistare un tomo sull'argomento e provare a falsificare delle monete.

**Mappe e Geografia**: Un tentativo di ricostruire le geografia del mondo, attuato da ogni biblioteca che si rispetti.
  - **Complicazione**: Più ci si allontana dal luogo dove sorge la Biblioteca più la vicenda è ambigua e approssimativa. 

**Fisiologia e Informazioni Razziali**: Spiegano le differenze tra le varie Razze, il comportamento nel dettaglio delle razze  minori,  cioè Elfi, Dragonidi, Tiefling,  Orchi, Gnomi e altri. 
- **Complicazione** Se è stato s critto da un razzista, potrebbero esserci delle approssimazioni. 

##### # **6. Conoscenza: Magica**

Questa sezione contiene testi scientifici, filosofici e magici. È il cuore dell'erudizione e della magia teorica. Sezioni molto raramente trovate.

**Teoria della Magia**:  Tomi complessi che trattano le teorie magiche e gli incantesimi. Qui si trovano descrizioni di rituali, Arti occulte, incantesimi e teorie sulla manipolazione dell’energia magica. Viene spiegato anche accenni di Cosmogonia, Metalli magici, Gerarchia della Magia e Linguaggi Arcani

**Trattati Arcani**: Spiegano il funzionamento degli Incantesimi nelle Tre Scuole. 
  - **Complicazione**: Un mago potrebbe trovare anche delle migliorie ai propri incantesimi, col rischio di rovinarli. A lui la scelta. 

**Trattati Runici**: il testo cerca di spiegare in modo approssimativo e cifrato qualcosa su di una runa. Comunque è necessario conoscerne già il nome o la forma.
