---
title: "Ruolo di gioco"
format:
  html:
    theme: default
---
Alcune costruzioni del personatggio danno accesso a un determinato ruolo di gioco. 

In Generale si può riconosere un ruiolo senza tante cerimonie, cioè davanti a un "posso essere l'investigatore della città?" non ho motivi per dire di no. Magari mi assicuro che non abbiuate la buiild di un barbaro razziatore, ma in linea di massima si può dire di sì e basta. ù

Alcuni ruoli però hanno un valore più rilevante per l'ambientazione in generale, per questo non posso semplicemenete dire di sì, senza che ci assicuriamo che sappiate cosa significa e che abbiate la build almeno adeguata per giocarla. 


<div class="pg-only" style="display:none;">
  <p>Contenuto segreto per PG</p>
</div>

<div class="dm-only" style="display:none;">
  <p>Contenuto per DM</p>
</div>

### Bardo 

Se avete il sogno bardico siete un bardo, avete cioè ricevuto l'addestramento da Bardo. In ogni città in cuio andrete, se vi farete riconsocere come Bardi, vi porteranno rispetto. Gli altri Bardi del mondo vi riconosceranno e così molti altri npc avranno rispetto del vostro ruolo. Ottenete queste capacità

- Puoi vedere l'irradion tirando di Carisma, e provare a dominarlo.
- Hai accesso ai file di Istruzione Magica
- Hai vissuto il Battesimo del Lago Bianco (vedi file apposito)

### Pirata

Se hai preso Marinaio puoi chiedere di essere un pirata. 

- Hai accesso a una nave, nel ruolo che preferisci
- Disponi di contatti nei traffici mercantili illegali e/o legali
- Conosci le rotte per navigare nel mondo, che hanno un altissimo valore dal punto di vista commerciale 

### Venator

Se hai un numero sensato di capaccità da cacciatore, puoi esserte un Venator. ù
I venatores si dividono a seconda della caccia di pertinenza (Vampiri, Draghi, Demoni, Bestie)
Ottieni quanto segue

- Accesso alla Lore dei Venatores
- Devi rispettare il Codex Venatorium, come spiegato nel file della Lore
- Hai accesso ai Rifugi dei Cacciatori
- Equipaggiamento specifico a seconda della categoria, vedi sotto 

#### Cacciatore di Vampiri 

Un cacciatore di vampiri possiede le seguenti abilità e strumenti:

- Percezione dell’aura: un venatores specializzato riconosce a occhio nudo quanta aura possiede un vampiro in una scala da 1 a 20. 20 non è il tetto massimo, è solo il tetto massimo percepibile dal cacciatore.
- Percezione magia vampirica: può tirare per cercare di capire se il vampiro che ha di fronte può accedere all’aura di un mago (che sarebbe molto pericoloso, ovviamente)
- Possiede tra il suo equipaggiamento una spada o altra arma di argento.  (che tiene in un fodero che li maschera all’olfatto raffinato dei vampiri) (Le armi in argento triplicano il danno inferto ai vampiri)
- Possiede anche una catena di Argento di 12 metri, utile alle sue operazioni di caccia ai vampiri.
- Ha avuto la grazia di sviluppare l’immunità al loro specifico anestetico
- È in grado di creare un Cerchio alchemico: un perimetro entro il quale la capacità del vampiro di accedere all’aura è molto indebolita. Per attivarlo deve preparare con dei rituali magici che gli sono stati insegnati di cui non conosce il significato, ma sa replicarli. L’area si estende per una trentina di metri di raggio, e viene preparata in un paio di minuti.
- Tecniche di caccia condivise: se ha tanti aiuti, può utilizzare delle catene fatte in solo argento (dal costo molto molto elevato) per imprigionare un vampiro. Questo può avere molti benefici per reperire informazioni.
- Fiale di Veleno per vampiri (di quello autoiniettabile): se il vampiro ti beve mentre l’hai in corpo dovrebbe perdere conoscenza. Hai avuto la grazia di sviluppare l’immunità anche a questo veleno.

#### Cacciatore di Demoni

Sei equipaggiato con un arma in Argento Bianco 

L'argento Bianco è un materiale a base argento ( quindi un sottoprodotto del [[Pavranio]] come tutti i metalli) infuso col sangue degli angeli. Queste armi hanno la proprietà di poter colpire 
- gli [[Dèi]], anche se si tratterebbe di una mossa suicida, 
- i [[Mannari]] più come effetto collaterale che voluto, 
- i [[Tiefling]]( e sono infatti in dotazione ai [[Cacciatore di Tiefling]]) visti inizialmente come servitori degli dei della Luna.  

Come caratteristiche generali invece
- Un'arma in argento bianco non può essere danneggiata in alcun modo.
- L'argento bianco ha come altra caratteristica notevole quella di lasciarsi incantare con molta facilità, offrendo poca se non nulla resistenza ai sovraincantamenti senza alcun limite.

Inoltre, ovviamente conosci il Demoniaco

#### Cacciatore di Draghi

Ottieni i seguenti vantaggi

- Conosci il draconico
- Tu hai l'addestramento di primo livello per l'utilizzo del sangue di drago. Qualsiasi classe costruirai, avrai a disposizione tre boccette iniettabili col seguente effetto: 
	"Per 5 turni ottieni le seguenti caratteristiche 
	- +30 punti ferita 
	- +4 ai tutti i danni inferti 
	- +2 ai tiri per colpire 
	- non puoi essere spaventato 
Una volta esaurite le boccette devi trovare un rifugio da Venatores e io vedo se te ne danno altro tirando. Come regola non ne si dà più di tre alla volta, perché sono molto costose. Ne puoi usare una per riposo breve. 

- Giacca di pelle di drago (la prima vittima che hai fatto), ignifuga, armatura media. 

- Dardi per balestra in [[Meteorite]] che hanno qualche porbabilità in più di perforare le scaglie dei draghi. 

- Arpione retrattile


#### Cacciatore di Bestie

Sei stato addestrato alle seguenti capacità 

- Tecniche di caccia avanzate (Vedi File Venatores)
- Ottieni Parlare con animali 
- Ottieni uno sconto del 50% in tutte le erboristerie (non valido per Infusioni)