---
title: "Filtri e Pozioni Avanzate"
format:
  html:
    theme: default
---

#### Sangue dell'avarizia 

Per la prossima ora, il modificatore del tuo tiro di combattimento è 1.  

Ogni volta che un nemico ti colpisce, ottieni +1 alle prove di combattimento e il tuo avversario prende -1. Inoltre, aggiungi quel bonus ai tuoi danni dell'arma. 

#### Neralbo liquido 

Fai colare il liquido a terra. Attivi l'incantesimo Neralbo.

#### Inchiostro di Keleborn

Evochi ali d'uccello nere, magre e ossute sulla tua schiena. In un area di 6m i tuoi nemici subiscono 2d6 danni necrotici per 1 minuto. Ogni creatura fa INT contro il tuo Carisma per non  essere spaventato da te. 

**Infusione**: può essere infuso su armi o armature, l'effetto dura però 3 turni, ed è riattivabile al prossimo riposo lungo. 

#### Overdrive

Ottieni +8 a tutte le statistiche e 50 pf. Per 1 ora non puoi usare capacità o incantesimi.

#### Forza di Trista 

Puoi eseguire la breccia come i monaci per un minuto. Non è eseguibile in figth. 

#### Lacrime di speranza

Per un minuto puoi pagare un pf permanente (massimo due volte a turno) per ritirare un dado, usi il risultato che preferisci.

#### Dammi la mano 

Il player colpito non sa quanti pf ha. Il master gli dice che ha 1 pf, senza fornire altre spiegazioni. (Stratega viene tratto in inganno). IlDM tiene conto dei suoi pf, sia che beva pozioni sia che prenda danni.

NB: master si consiglia di chiedere "quanti pf hai? Armature?" Prima di dirgli "hai 1 pf"