---
title: "Oggetti"
search: false
format:
  html:
    theme: default
---

- Anello **Ossessione del Cacciatore**: autorità di un dio, scegli una vittima (una vittima deve essere ingaggiata con te) La vittima ha un grande freddo.. Ogni volta che vieni colpito da qualcuno dievrso dalla vittima, metà dei danni prearmatura vengono trasmessi alla vittima, a meno che non sia la vittima a colpirti, in quel caso i danni sono raddoppiati. Puoi cambiare la vittima una volta a round con un'azione bonus. Se la vittima disingaggia, non è più tale (richiede _Sintonizzazione_)

- Spirale dei **Razak**: se vieni colpito, puoi usare una reazione e scegliere un avversario che puoi vedere. Una serpe di vetro esce dalla spirale, si snoda dal bracciale e parte verso la vittima, ingaggiandolo, e cercando di colpirlo (usa la tua intelligenza, due distanze). Se colpsice, si aggrappa a un arto, rendendo impossibile l'utilizzo dell'arto o di qualsiasi cosa vi fosse attaccato. Se viene distrutto (azione) si rompe come vetro, e si riforma sul tuo braccio. Può essere usato fino a 8 volte a fight. Autorità della magia.