---
title: "Cerbero"
format:
  html:
    theme: default
---

Grado: Vissàl
Titoli: il nero Segugio,  Diavolo della Fame

Cerbero ottenne la capacità di trasformarsi in un Mollosso. Inoltre, fu in grado di sviluppare un veleno per il quale poteva trasformare una vittima in un Molosso a sua volta. Questo appartiene alla grande mente alveare che è Cerbero. Cerbero è noto come "Il Diavolo della Fame", fa la sua comparsa in grandi guerre di cui sente l'odore, schierato da entrambe le parti, per poter accrescere le sue fila. 

Per uccidere una testa di Cerbero è necessario dell'Argento Bianco, altrimenti una volta ucciso sis rigenera in qualche giorno. 

La grande terribile efficacia  di Cerbero, il motivo per cui non si riesce a uccidere è che non ha un corpo principale, e sppeur guidato dalla bramosia di uccidere, è ancora un essere furbo, in grado di captare magia. Si chiama il diavolo della fame perché per non eprdere i sentimenti anche lui si è rifugiato in un destino nefasto, cioè di lasciarsi consumare dalla fame, che, di anno in anno, cresce, perché la maledizione dei Tiefling non si estingue. 

Appare anche nella sua forma di Tiefling, ma soltanto ad un altro Tiefling, per cui nutre una certa simpatia, come tutti i Diavoli. 

Inoltre, quando più teste sono tra loro assieme ne guadagnano in forza  e resistenza. 