---
title: "Storia"
output-file: storia
search: false
format:
  html:
    theme: default
---

Chi ha studiato i rudimenti della storia (poche, ma poche persone) sa che l'orogine del mondo è perfettamente nota. L'inizion di questa storia,  per i pochissimi che sappiano leggerlo, è scritta sugli altari nei focolari della dea Estia. Pertanto, finché ci si fida di lei, e di chi ha messo insieme la storia, siamo certi di cosa sia successo. 

Lo storico Ethiam Set, il primo  bibliotecario, dopo aver collezionato i vari frammenti della storia, ci riporta una classica traduzione come segue.

### Orogenesi

Mortali della terra. Io sono nata che il mondo c'era già, e prima che il dio del tempo iniziasse a prendere nota del mondo, quindi io non so dare una ragione del tempo. Per questo non so dire quanto durò  l'orogenesi. 

Gli abitanti più simili a voi erano gli T'kalsis. Questi esseri non avevano capacità magica, ma erano forti, e di grandissima devozione nei confronti degli Dèi. Il potere gli fu donato dagli dèi per cui nutrivano la più grande devozione

- Estia, dea del focolare e della pietà, io che donai loro la pace nel cuore.
- Mondul, dio  della vita e della morte, che rese alcuni di loro immortali
- Seltan, dio dei mari, della navigazione, delle tempeste e  dei tesori sommersi.
- Selune, dea della luna, delle stelle, dell'ordine del cosmo, della caccia e delle bestie. 

Nel tempo, trovarono un'altra razza, più debole di loro, e su mio incoraggiamento, ebbero pietà di loro, e iniziarono a fondersi con loro, e generarono le prime due razze comuni

- Gli uomini
- I nani 

Ai tempi dell'orogenesi si crearono dunque Tribù, governate da questi T'kalsis, nomadi.

### Giorni senza nome

**Durata**: ???- poi da 0 a 2000 anno dell'Aurora

Nei giorni senza nome gli uomini e i nani vivevano in sparuti gruppi, ancora in Tribù. Ma poi due cambiamenti sconvolsero il mondo:

- 1: Gli uomini e i nani iniziarono a chiedere ai T'kalsis di poter vivere in uno stesso luogo, perché non riuscivano a vivere al loro ritmo. Così i T'kalsis chiesero mi chiesero aiuto, e generai per loro i _Grandi Focolai_. Luoghi protetti ove gli uomini poterono stanziarsi senza troppi pericoli.
- 2: Gli uomini, vedendo il loro numero crescere, e che i T'kalsis non riuscivano a proteggerli tutti nello stesso tempo, chiesero al dio Seltan la forza che dava loro quando dovevano attraversare il mare, di darla a uno solo di loro. Così gli uomini scelsero 10 dei più forti di loro  e li sacrificavano a Seltan, il quale dava loro indeitro un guerriero in grado di sopportare il freddo, la fame, la sete, e che gestisse le scotte senza fatica, che nuotasse senza avvedersene, che fosse forte, veloce, che vedesse di notte per guidarli nelle tormente e nelle tempoese. E così crearono gli _elfi_. Inizialmente dei paladini delgi uomini. 

### Era dell'Aurora Bianca

Con queste due armi a loro disposizione, gli uomini e i nani non avevano più bisogno dei T'kalsis, e nel tempo, cominciarono a crearsi comunità che riuscirono a farne a meno. I T'kalsis così a un certo punto sparirono, come avevano appreso da Selune, che insegna loro che i cuccioli che crescono vanno lasciati al mondo, e da Estia, che non avrebbe mai voluto che si scatenasse una guerra  per mantenere il loro potere, i T'kalsis se ne andarono. E non furono più visti su queste terre. 

Così iniziò un'epoca per gli uomini in cui essi furono sedentari. Da questo giorno Heluvian iniziò a contare il tempo, fino al giorno dell' **Aurora Bianca** (2000). 

Vivevano nelle città, protetti e guidati dagli elfi, e nei confini dei miei Grandi Focolari, e iniziarono a conoscere la magia. La curiosità  degli uomini non era come la devozione dei T'kalsis, gli uomini cercavano, creavano, sperimentavano. Creando e sperimentando, e interrogando gli dèi, analizzando le preghiere con atteggiamento di scienza, riuscirono a capire un po' della magia. Con la magia lo spazio che iniziavano a ritagliarsi nel mondo si faceva sempre più grande. Due furono gli eventi notevoli a questo punto.

- Gli [elfi](/capitoli/Regole/Classi%20Nascoste/elfo.html) divennero tanti, ma gli uomini e i nani, armati di magia, non volevano più lasciarli governare. Così gli elfli si rifugiarono sulle montagne, scacciata dagli stessi uomini che li avevano creati. Essi furono temprati dai climi aspri delle montagne di Irradan.
- Dagli uomini vennero generati i Draghi, il risultato di un esperimento fallito. Conosciuti di lì come la prima delle piaghe del Mondo.

### Epopea dei Re

**Durata**: 2000- 3500

#### Epopea della Luna Piena

L'Epopea dei Re inizia con le guerre degli Angeli. Queste guerre iniziarono quando Indra divise la divinità del Sole in 4, generando 4 divinità del Sole. Queste lottarono tra di loro per ottenere il dominio degli Angeli, l'esercito del sole. Alla fine Elìa ne uscì vincitore, e io, Estia, ne uscii estremamente indebolita.

Con la fine di questa guerra furono 2 le cose a cambiare definitivamente:

- Io, dea Estia che protegge gli uomini, caddi. Ciò portò alla fine dei Grandi Focolai. Dove cadevano i Focolai, se c'erano degli uomini abbastanza potenti per prendere il potere, venivano chiamati _Re_. 
- Con la divisione del Sole e il suo smembramento, la forza di Bora sul mondo si fece sentire di più. Quindi gli Elfi, che fino a quel momento erano rimasti silenti sulle montagne dopo la loro cacciata, sentirono l'esigenza di scendere. 
- (Inoltre, siccome la dea Selune ottenne il Sangue di molti Angeli, finalmente, illuminò la Luna, colorandola con la loro linfa. Da quel giorno essa è Luminosa. Per questo questa epoca viene detta anche Era della Luna Piena)

La portata di questo cataclisma fu tale che i Bardi iniziarono a crearsi e a diffondersi a partire da questo momento

#### Epopea dei Re

Cominciarono a sorgere i Re. Due tipi di Re

- I re delle Città: sostanzialmente dei maghi o stregoni che avevano acquisito abbastanza potere da mantenere un primato su di una città. Di Re ce ne furono senza dubbio molti, e molti caddero. Ma esistono dei Re che hanno creato un primato, ruolo che si trapassa di generazione in generazione.

	- Il Re Saggio: Re di Librio
	- La Sacerdotessa: Regina di Sorgiva (la prima cantrice dei Mari)

- Re delle forme: degli esseri a cui determinati luoghi, o gruppi, o fenomeni del mondo dovevano lealtà. Gli umani stipularono una magia con il dio del tempo Heluvian: se fossero compiute  imprese tanto lodevoli da meritarlo, il dio avrebbe concesso loro lo Stemma del re, che imponeva a un determinato rango di Inchinarsi  davanti al re. 

	- Re degli Elfi, che fu in grado di contenere  gli elfi entro i loro confini nella guerra che ne scaturì, la Prima Guerra Elfica.
	- Re dei Mari, che era in grado di moderare la pirateria tassando le città
	- Re dei Viandanti, che era in grado di contenere le stragi di nomadi, mercenari, zingari e lupi solitari, proteggendoli con le Vie Sicure 
	- Re dei Draghi, che era in grado di contenere la minaccia dei draghi
	- Re delle Ninfee, che fu in grado di contenere le ninfee come il  re degli elfi

#### Epopea Ultima  

Emersero i Re più recenti, che poi fondarono ordini o grandi casate

- Re dei Ladri, Rose Clairein 
- Re Protettore, Armando De Cervantes
- Re Probo, che fondò l'ordine dei Venatores
- Re Matto, recentissimo re Dei Sogni
- Re della Guerra, il Vecchio Freymar

### Epoca del Ferro 

**Durata**: 3500-8500

#### Età delle sciagure 3500-6500

Gli uomini iniziarono una serie di guerre di conquista tra loro. Nel farlo, persero la vita molti Re, e molti re delle Forme persero l'interesse nel proteggere il mondo, rilascciando le loro minaccia nel mondo:

- Ninfee
- Elfi
- Draghi
- Pirati 
- La perdita delle Vie Sicure nelle foreste e sulle montagne

Contemporaneamente comparvero  le seguenti sciagure 

- Vennero generati i Tiefling da parte della dea Indra
- Vennero generati i Vampiri da parte della dea Vengra, creando le prime  genitrici Nalara e Lahzara
- Giunsero su Perprimaria i Bruti, da terre sconosciute sbarcarono sul continente, portando alla rovina di molti regni. Numerosi gruppi sbarcarono, e numerosi regni ne furono devastati

Così questa era fu chiamata epoca del Ferro a simboleggiare

- La fine dei Re: infatti non ci sono più corone dorate a simboleggiare i Re, ma i reggenti delle città hanno simboli in ferro
- I metalli, le tecnologie, le nuove magie (la scoperta che la magia è un metallo viene diffusa nelle accademie), e i nuovi stili di governo, più flessibili anche se instabili che caratterizzano adesso le città al posto dei re
- l'inizio delle guerre che seguirono

#### Età degli ordini 6500-8500

A seguito di questa epoca di assoluto disordine ci furono due importanti cambiamenti

- Fondazione del mio Ordine, l'_Ordine dei chierici di Estia_ per creare i suoi Piccoli Focolari, sulle ceneri delle Vie Sicure, per cercare di creare piccoli angoli di pace nel mondo
- Seguirono due ordini magici, che non tentavano più la riscoperta di antichi  saperi perduti di magia, ma ne fondarono di nuovi. L'età degli ordini inizia infatti con la fondazione del primo 
	- Ordine dei maghi di Merlino
	- Ordine dei maghi della nuova era|ordine dei maghi da battaglia
- L' ordine dei _Venatores_ decide di ampliare la propria missione a tutto il mondo 
- I _Bardi_ nel loro complesso, pur non essendo un ordine, da che si erano creati dopo le Guerre degli angeli, presero a cuore il compito di diffondere la conoscenza per il mondo 
- Le _Sette biblioteche mobili_ decisero di aprire dei varchi nel mondo per provare a raccogleire la conoscenza che si poteva ancora recueprare.

Questi cambiamenti riuscirono a mitigare la tragedia, a costituire una qualche forma di spinta, di ripresa, ma sempre si parla di una situazione tragica, quella in cui versa ail nostro mondo. 