---
title: "Angeli"
format:
  html:
    theme: default
---

Gli angeli tutti riposano sulle [[Rocche del sole]]

Prima sfera
- Serafini: grandi esseri (tipo drago Orientale) con sei paia di Ali, le lunghe corna da cervo. ai tempi in cui il Dio Elios era in vita, egli sentiva la necessità di fare in modo che la sua luce trapassasse tutti gli esseri Celestiali, così creò i raggi solari. Ecco cosa sono i Serafini. Sono ciò che congiunge la terra al sole. Di più, si può parlare di loro come delle creature alate di forma serpentina, ma trascendono questo concetto, tale è la loro magia. vengono riportati nomi noti
	- Eraphiel – "Fiamma Celeste"
	- Raziel – "Segreto della Luce"
	- Auriel – "Alba Eterna"
	- Thaliel – "Raggio Divino"
- Cherubini: furono tutti annientati. Di essi si conserva il sangue, perché erano tra i più letali combattenti. Diversi manufatti furono creati utilizzando il loro sagnue. 
	- Spada Orgoglio del Cherubino ( aggiornamento: vedi [[Spada del Rancore]])
	- [[Spada del Mezzogiorno]]
	- [[Scudo del Sacrificio]]
	- [[Diadema dell'Orizzonte]]
	- [[Lira della Guerra]]
	- [[Calice della Pace]]
	- [[Catene e Sentenza]]
- Troni: Ruote infuocate ricoperte di occhi, sono controllori degli angeli. Inoltre, sono coloro che mantengono gli esseri Celestiali lontani dai confini del mondo sui Picchi più alti dei monti. vengono riportati nomi noti
	- Caeltharion – "Guardiano dei Cieli"
	- Valakiron – "Araldo delle Stelle"

Seconda sfera 
- Dominazioni: annientati. Tutti annientati. Alla loro morte, alcuni vennero raccolti, tenuti entro delle bare, e su di loro fu forgiata una dinastia, la dinastia degli [[Autoritas Regium]]
- Virtù: coloro che spostano il sole in varie angolazioni per regolare le stagioni, e consentire il crescere di certi frutti. Erano un esperimento di Elio.
	- Kena'hei– "Vegliare delle Sfere"
- Potestà: i più intelligenti, e calcolatori, e saggi. Hanno studiato più di tutti. Le [[Rocche del Sole]] conservano le Potestà a cui appartengono i sette libri che danno forma alle [[Sette biblioteche mobili]]. Vengono riportati i nomi noti 
	- Eryndoriel – "Custode dell’Equilibrio"
	- Elysariel – "Benedizione d’Oro"
	- Mythrion – "Scudo della Verità"
	- Ya'dhal – "Cantore dell’Eterno"

Terza sfera
- Principati: tutti annientati. Il grande dio del tempo, [[Dèi#Heluvian|Heluvian]] a suo tempo raccolse le corde vocali di questi angeli, così riuscì a conservare la maggior parte dell'autorità che si possa immaginare sul tempo, poichè questi angeli sovraintenedvano a parte del suo funzionamento. ora quelle corde vocali sono intessute nello strumento etterno del dio del tempo. 
- Arcangeli: capi degli angeli, dall'immenso potere distruttivo. Quando si parla della distruttività degli angeli, le perosne intendono al massimo comunemente loro. Dopo la sua presa di potere, Elìa fece in modo che gli Arcangeli si riproducessero, e fondò su di essi la fama di morte delle [[Rocche del sole]]. vengono riportati nomi noti
	- E'lha'Tau – "Araldo della Gloria Divina"
	- Orione – "Stella Guerriera"
	- Zarathion – "Folgore Giudicatrice"
- Angeli: bellissimi come li abbiamo in mente, potenti guerrieri e liberi di girare nel mondo. Cercano chi creda nel dio Sole, possono prediligere alcuni umani e alcune città, li comunicano agli Arcangeli. Oppure no. Se vogliono, se riescono. Fanno un po' quello che gli pare. Non sono distruttivi come gli Arcangeli, ma sono immortali, quasi indanmeggiabili. A volte diventano Custodi. 

Accade alle volte che essi seducano un mortale, dando vita a un [mezzosangue](/capitoli/Regole/Classi%20Nascoste/nephelim.html)