---
title: "I Bardi"
search: false
format:
  html:
    theme: default
---

La Storia dei Bardi si allaccia a doppio manto a quella delle Fate. 

### Fate

Le Fate sono esseri generati dalla fusione di Neon e Oricalco. La loro alta concentrazione di Neon le rende altamente instabili, inclini in un certo qual modo alla follia. La cosa terrbile delle fate è che sono estremamente ribollenti di Oricalco: pare che loro riescano a muovere, proprio grazie appunto al Neon, enormi quantità istantaneamente di Oricalco, ma che essendo poca la Giada che le costituisce, non siano chiare le loro intenzioni neanche a loro stesse ogni tanto. Pertanto, accade che le loro magie siano imprevedibili, folli, e che abbiano alterato la Lingua degli dei.

Le Fate nella loro follia, nella loro modifica della lingua degli dèi, hanno accesso a un modo tutto loro di pensare, unificato, in un grande sogno collettivo, in una Mente Alveare, che dà  un senso ai loro sogni. Sognando, muovono con il loro potere molto metallo, generando un mondo parallelo, detto Vanghaal. 

Il potere dei bardi è a loro legato, perché i Bardi, potendo cantare alle frequenze dell'Irradion, danno un ritmo ai loro sogni, una forma ai loro sogni. Per questo si perde il confine tra quanto le leggende dei bardi siano vere o meno, perché ove credute dalla fata, potrebbero finire nel sogno, e diventare vere nel Vanghaal, o addirittura nel mondo vero.

Non c'è uomo che non debba temerle. Tranne forse i Bardi. Infatti le fate non attaccano i Bardi, almeno, se non provocate.  

Le Fate risiedono tutte, o quasi almeno, a Croce dei Popoli 

Uccidere una fata rappresenta un crimine per tutte le altre, poiché le volontà delle fate sono così sparpagliate che sono condivise parzialmente dalle altre. Si diventa nemici dell'intero popolo. 

Le fate vengono in ranghi a seconda della concentrazione di potere. Queste concentrazioni sono approssimazioni, più utili alla comprensione, che non a una reale misurazione.

#### Croce dei Popoli

Un lago molto importante dove antichissime [[Balene celesti]] si agitino, molto potere è contenuto all’interno e si dice sia benedetto. Si dice che le [[Fate]] origino da qui, e che qui risiedano. A croce dei popoli sono successe così tante cose importanti che non è possibile dimenticare questo lago e non considerarlo. I popoli che ci vicino vicino gli danno un ruolo sacro, e pare che, nonostante questo lago difenda le città che lo abitano, che sono in effetti millenarie, cancelli i loro ricordi come cultura, rendono ancora una volta impossibile tracciare una storia. 

[[Ali Manora]] e [[Linzia]] sono le due grandi regioni influenzate da questo lago. 

##### Lago Bianco

Al centro di Croce dei Popoli si dice esista un'isola nella nebbia, molto grande, detta l'Isola dei Salici Piangenti, all'interno della quale vi sia un lago, detto il [[Lago Bianco]].  All'interno di questo lago si dice vivano le Fate. 

Lago all'interno dell'isola della [[Croce dei Popoli]] Le leggende leggende dicono colleghi il nostro mondo alle terre del Vanghaal, luogo nato dalle leggende cantate dai Bardi, l'esagerazione di un mondo che non esiste. Infatti il mondo creato da i bardi rassomiglia in certi punti al nostro. Chiunque acceda a quel mondo, si dice che stia vivendo il "Sogno delle Fate", un mondo a specchio dentro il nostro mondo, con però così tanto potere da essere reale: qualcosa che giunga dal "Sogno delle Fate" è solo stato generato dalle Fate, ma esiste, non di meno. All'interno di questo lago sicuramente vivono le Fate. 

Al controllo dell'accesso del lago c'è [[Delgaren II]].

Bere l'acqua di questo lago rende immortali, almeno finché esiste la fata, o le [[Fate]] che aveva pianto quell'acqua. 

Entrare all'interno del Lago Bianco significa, data la concentrazione di Neon, che lo spazio è distorto al suo interno. E pertanto non è possibile capirne le dimensioni. 

#### Ranghi 

Le fate si dividono in ranghi a seconda della vicinanza alla Mente Alveare.

 - **Primigenee**: 
  Estremamente pericolose e potenti, e folli oltre ogni dire, la loro quantità di Neon le rende folli.
 - **Strateghe**: 
  Le Strateghe hanno meno energia di tutte, ma hanno assorbito gli elementi per poter dominare le loro sorelle più grandi, probabilmente Taddìma, e pertanto le governano. Si dice che abbiamo le sembianze di statue semoventi.
 - **Violente**: 
  Probabilmente le fate più bilanciate, perfette per essere ciò che le leggende temono di raccontare, e anche le più comuni.
 - **Sapienti**:
  Le fate con minor concentrazione di Neon, che consente loro di poter ragionare con gli umani. Sono nate con l'intenzione di poter interagire col mondo narrato dall'Irradion, e pertanto assumono un corpo fisico. All'apparenza infatti sono normalissime persone. I Figli di fata infatti, originano da loro.
 - **Innocue**: 95% Neon, 4% Pavranio, scarti di Oricalco e meno di un'ombra di Giada. 
  Assumono la forma di farfalle e si sparpagliano per il mondo. Hanno troppa poca Giada, poca volontà per fare del male a chiunque. Sono una manifestazione del potere delle Fate. Fate Sapienti sanno utilizzarle per teletraportarsi istantaneamente nei pressi delle Farfalle Blu, se in quel momento sono in collegamento con loro e sono vicine. Solitamente quando un Bardo ne vede una può provare a catturarla e recuperare il suo potere: questo è in grado di generare un'energia benefica per sè e per chiunque il bardo possa raggiungere con l'Irradion. Rimane una versione in un metallo povero ma luccicante della farfalla. 



