---
title: "Celestiali"
format:
  html:
    theme: default
---

## Bestie conosciute 

Mante Celesti: prigione di An-Sur
Meduse
Pesce lanterna: 

Chi ne viene a contatto testimonia una caratteristica del Miasma cioè quella di attaccarsi in modo molto più instabile alle cose. Come se parassitasse le cose, come se le consumasse una volta che vi si fosse attaccato.

Se non si è studiato in modo approfondito l'Occulto, per altro, il miasma viene facilmente scambiato per Oricalco comune.

La sola presenza di grandi quantità di Miasma è in grado di alterare in modi strani e macabri il tessuto del mondo. Luoghi esposti a questo tipo di magia potrebbero essere vittima di strane piaghe, distorsioni della percezione del mondo o delle leggi della natura.

- _Urania:_ 

- _Cronomalia:_ Nautilo

- _Orbis_: 

- _Ardere malefico:_ 

- _Neralbo:_ Polpo
 
## Bestie che hanno raggiunto la terra

*Drago Bianco*: una est

*Kyronia*: Questo essere è un lupo serpentino, con tante lunghe zampe di ragno, che tessono filamenti d'acciaio sottilissimi imprigionando [[Nalara e Lahzara]] nella [[Torre di Jedis]]. Kyronia era stato evocato da [[Merlino]] e condannato a questo uffizio di carceriere. Pertanto non è possibile che non abbia sempre attivi 5 prigionieri. Se ne si vuole liberare uno, bisogna portarne almeno un altro. 

*Bestia di Eld*
Puoi richiamarla e offrire un tributo: non durante la tua ultima sessione, se possiedi un artefatto, puoi mandarlo al personaggio della tua prossima run. Una sola volta per run per giocatore, trovandosi davanti a un Altare di Eld.

In alternativa può anche essere messo nella Tana di Eld (Pool comune a tutti i giocatori) ottenendo qualcosa in cambio messo alla Tana di Eld.

L'item può subire danneggiamenti o modifiche nel frattempo.

- Orologio di Thataghzaghal: segna un check point
- L'abito fa il monaco: sei credibile per quello che vuoi fare nel momento in cui lo stai provando a fare