---
title: "Bestiario del Cacciatore"
search: false
format:
  html:
    theme: default
---

**Neythune:**
Ragni dalle zampe in avorio, e il corpo come una sorte di conchiglia trasparente. Al loro intrno brilla una piccola luce arancio. Questi ragni hanno dimensioni di un palmo finchè sono piccoli, e crescono fino alle dimenzioni di un cavallo nell'arco di pochi anni. Si muovono in gruppi da massima una ventina di esemplari. 

Iniettano un veleno che è in grado di eliminare i ricordi alle persone. Il DM  decide quali ricordi sulla base di un tiro, ma tipicamente più il ragno è grande maggiori e più profondi sono i ricordi. I Ricordi vengono storati all'interno della loro conchiglia, rompendo la quale (o uccidendo il ragno) si distruggerebbero i ricordi definitivamente. pertanto devono essere catturati, e bisogna estrarre il globulo di ricordi e riavvicinarlo all atesta della persona. La persona a cui appartenevano i ricordi, avrà comunque idea di dove si trovino i suoi ricordi per una certa quantità di giorni. 

Se il ragno viene danneggiato, la persona a cui appartenevano i ricordi subirà gli stessi danni (e viceversa) per un paio di giorni.

Se lasciati a sè stessi però, questi ricordi vengono condensati in delle perle, che poi vengono utilizzati per fare una struttura vicino a una fonte d'acqua, utile per l'accoppiamento. Questo è il motivo per cui alcune di queste perle si posson o trovare vicino al mare. 

Inoltre, da tipo di mostri il demone Terebrissa ha saputo sviluppare alcuni incantesimi di memoria. Nonché questi ragni vengon utilizzati per produrre l'Illantina.