---
title: "Espero"
format:
  html:
    theme: default
---

### Kanjur il profeta

Millenni orsono Espero ha trasmesso il suo verbo per tramite di un profeta che si è scelto lui. Di questo profeta non si sa il nome o il genere, lo si chiama Kanjur, un nome che non è solo maschile o femminile. Ciò che diceva il profeta è stato trascritto dai discepoli che aveva raccolto, il testo sacro frutto di questo lavoro di trascrittura è il Canone Esperiano o Bka’-’gyur (la parola è nella lingua in cui parlava Kanjur e significa La raccolta delle parole tradotte di Kanjur). 

#### Il messaggio di Espero

Nei testi sacri è spiegato che Espero è il Dio che garantisce l’alternarsi del dì e della notte, il simbolo evidente del fatto che nell’universo tutto è coinvolto da un perpetuo processo di cambiamento. L’alternarsi del dì e della notte rammenta a tutti gli uomini questo processo, che tutto è coinvolto in questo processo. 

Ma non si tratta di un processo lineare, bensì ciclico, com’è ciclico l’alternarsi del dì e della notte. Espero non è semplicemente il Dio dell’alba e del Tramonto (che comunque è cruciale nel mondo in cui viviamo), perché è innanzitutto il dio del *panta rei*, il dio che vigila su quel continuo processo di cambiamento che è l’essenza della vita stessa. Questo processo non è semplicemente buono o cattivo ed è ben simboleggiato dal ciclo giorno-notte: la notte non rappresenta il male e il giorno il bene, non c’è una rappresentazione manichea della realtà, in entrambi ci sono sia il bene sia il male (yin-yang freebooter N.D.A), sono due parti della stessa cosa, non separate, è una totalità, e si sostengono a vicenda. 

- La notte è più vicina a ciò che di negativo c’è nel mondo, nell’oscurità non vedi, si può annidare un pericolo ecc, ma di notte c’è anche vita, ci sono gli animali notturni, c’è il sonno ristoratore ecc. 
- Il giorno è più vicino a ciò che di positivo c’è nel mondo, il sole che coi suoi raggi dà la vita, fa crescere le colture, ma può anche rappresentare la siccità, il bruciore e così via.

In sintesi, l’insegnamento cruciale di Espero è: *accettare la transitorietà di tutte le cose*, umani compresi, e capire che nel male c’è il bene e nel bene c’è il male, se fai ciò vivi meglio (per attirare gente serve che tu gli offra una via per vivere meglio N.D.A)

Se in un posto non sorge più il sole crolla tutto il sistema.

#### Frammenti del Bka’-’gyur

**Panta Rei**: 

Ed ecco il dio di ogni movimento mi parlò e si presentò a me con queste parole 

"Sono la tua ombra interiore, quella che ride dell'illusione che chiami realtà. Paziente come un ragno, incastonato come un gioiello in ciascuno dei tuoi attimi, condividi la tua vita con me; se ti rifiuti di farlo, non vivrai mai veramente. Potrai andare a nasconderti in capo al mondo, io sarò sempre al tuo fianco. Da quando sei nato, sono la madre che continua a toglierti alla luce, quando sei accecato, e a rendertela, quando sei perso nel buio. Rallegrati dunque! Soltanto quando mi concepisci la vita ha un senso. Insensato è chi non mi riconosce e si aggrappa alle cose senza accorgersi che appartengono tutte a me. Non ve n'è una che non abbia il mio sigillo. Permanente impermanenza, sono il segreto dei saggi: essi sanno che possono progredire soltanto percorrendo la mia strada. Coloro che mi assimilano diventano potenti. Coloro che mi negano, nel vano tentativo di fuggire da me, si perdono le delizie dell'effimero: sono senza sapere di essere. Non vivono, ma la vita li vive"

"I bambini non riescono a immaginarmi. Se potessero farlo, non sarebbero più bambini, perché sono la fine dell'infanzia. Chi mi incontra lungo la strada diventa adulto. Divoro le sue difficoltà, i trionfi, i fallimenti, gli amori, le delusioni, i piaceri, i dolori, i genitori, i figli, l'orgoglio, le illusioni, la ricchezza. Tutto vi tolgo e vi rendo, perché nulla era vostro o mio, ma tutto passa per voi tramite me. Grazie a me tutto diventa polvere e tutto affonda. Rallegratene: se così non fosse non vedresti il Vuoto oltre il Cielo, se fosse pieno di polvere. Faccio della distruzione un processo di grande splendore. Aspetto che la vita si manifesti fino a raggiungere il massimo grado di bellezza, e allora la consacro. Quando giunge al limite della crescita, non lascio che si fermi e smetta di partecipare del mondo, invece gli dono altlra luce, ancora giro tutte le facce del dado, perché possiate vederne tutto lo splendore. Che gioia! Che gioia incommensurabile! La mia distruzione permanente apre la strada alla costante creazione. Se non c'è fine, non c'è inizio, fine e inizio sono in realtà la stessa parola. Ecco, quella parola è **Byur** . 

_(NDT: Byur è altrimenti tradotto "Diventurare". Bka e Gyur sono due neologismi del Kanjur, per dire inizio e fine a partire da Byur)_

"Sono al servizio dell'eternità, o meglio dell'etterno svolgersi. Sii forte! Vivi accanto a me! Chi cammina con me trasforma i figli, gli amici, la patria, il mondo. Se ti identifichi con la tua coscienza, avrai paura di me. Se sacrifichi la tua coscienza, cedendomi l'ultima delle tue illusioni — quello sguardo che vuole tutto e crede di vedere senza essere nulla — mi sconfiggerai. Sono la porta divina: chi entra nel mio territorio è un saggio, e chi non riesce a varcare la mia soglia in piena coscienza è un bambino impaurito che si fa scudo con i propri detriti. In me si deve entrare puri: liberati di qualunque cosa, liberati anche del distacco, devi annichilirti. Quando sarai sparito, comparirà Dio."

"Se diventerai il mio amante, vivremo assieme dell'amplesso tutte le parti, dalla seduzione alla piccola morte. Vivremo insieme il fecondare, la gestazione, il dare alla luce, e il seppellire. Quando senti che faccio parte del tuo corpo, tra-sformo l'idea che hai di te stesso, ti rendo morto in vita e ti regalo lo sguardo puro dei morti: due fori senza punti di fissaggio attraverso i quali guarda soltanto Dio."

"L'attimo è allora terribile, tutto si trasforma in uno specchio e ti vedi in ciascun essere, in ciascuna forma, in ciascun processo. Quella che chiami vita, diventa un verbo in svolgiimento. Quello che chiami argine diventa fiume." 

"Non tremare, non avere paura, rallegrati! Dandomi il tuo sguardo capirai finalmente quale miracolo sia essere vivi. In me non sarai persona, sarai il **Diventurare** . Ed esso dura finché avrai capito che non sono tuo, ma sono tramite te."

**Testo 2** su yin e yang freebooter

Ed io gli dissi "Ecco, non capisco. Sei cosa, il tempo o le cose? Se in me o sei me?" Ed egli mi rispose

"Sono qui, davanti a voi, intorno a voi e dentro di voi, con immenso piacere. Sono un essere completo. In me non v'è nulla che mi opponga resistenza. Tutto è unità. Sono la danza perpetua della totalità. Ma chi diventa completamente puro e concavo, chi mi lascia entrare dentro di sé, comincia a danzare insieme a me, a dire quello che io dico. E costui conosce l'amore universale, il pensiero totale, il desiderio cosmico, la forza di vita impensabile. Costui conosce la **quinitienza**, l'unità di tutte le energie."

(NDT: quinitenza è una translitterazione, ma ancora non si capisce cosa significhi)

"Se riesci ad arrivare fino a me, se mi sviluppi dentro di te, potrai assaporare la gioia suprema che è la gioia di vivere. Ma per farlo devi dissolverti nel gioiello ardente della mia presenza. Come quattro fiumi che ritornano all'unica sorgente, lascia che i tuoi concetti, sciame di api cieche, si fondano nella mia felicità. Lascia annegare il gregge dei tuoi sentimenti nella mia esaltazione infinita; offrimi il branco impazzito dei tuoi desideri perché possa arricchire, come un manicaretto prelibato, la mia costante creatività. E lascia che l'intera tua materia, con i suoi inevitabili bisogni, si abbandoni alla trasparenza che mi anima. Allora sarai padrone del tuo universo. Nel tuo intimo, la libido non si agiterà più, le tue passioni non potranno travolgerti, i tuoi pensieri non ti distrugge-ranno e il tuo corpo non ostacolerà la tua essenza. Sarai pieno, unito a me nella danza, nel godimento, nella festa incommensurabile."

"Mediante l'obbedienza faccio sì che il tuo intelletto impari a essere mediante la pace assoluta faccio sì che il tuo cuore impari ad amare; mediante l'apprendimento della ricezione faccio sì che il tuo sesso impari a creare; mediante l'accettazione della morte faccio sì che il tuo corpo impari a vivere. Se tu, come un leone affamato e assetato, abbandoni la preda per innalzarti verso l'anima, alla fine mi troverai. Sono il piacere di vivere e della realizzazione. Sono il fiore effimero che nasce costantemente dall'abisso; rappresento la materializzazione di tutti i sogni, l'anima senza la quale il mondo non è mondo ma un deserto sterile, la fine della speranza. Sono la meta di tutte le strade. Gioia ineffabile."