---
title: "Guerre degli Angeli"
search: false
format:
  html:
    theme: default
---

### Guerre degli Angeli 

La guerra degli [Angeli](/capitoli/Lore/Approfondimenti/Lore%20Nascosta/angeli.html) si combattè nella Zona Celeste. Questa guerra si combattè per gli Angeli. Lo stesso controllo degli angeli era il motivo della guerra, eprché a chi avesse più angeli sarebbe chiaramente andata l'autorità del Sole. 
Durante le guerre degli Angeli questi furono gli schieramenti, in modo che la maggior parte degli angeli di una categoria, siccome erano molto simili, si schierarssero con un dio.

Estia: Prinicipati, potestà, virtù
Espero: *Cherubini*, Angeli. 
Allumi: *Dominazioni*, Troni
Elìa: Serafini, Arcangeli

Iniziaalmente la guerra sembrava in mano ad Estia. Ella aveva un buon progetto e molti si erano schierati a suo favore. Ma Ya'dhal profetizzo ad Estia che Elìa avrebbe trovato il modo di fare riprodurre gli angeli, e che rpesto avrebbe avuto nuovi Serafini, e molti e molti più Arcangeli. In questo scenario, Elìa avrebbe distrutto tutte le forze del sole. Estia cercò allora di prevenire la catastrofe, cercando di allearsi con Elìa, promettendo che sarebbe diventata sua sottomessa. Elì accettò, e inflissero insieme  duri colpi alle forze di Espero e Allumi, ma si alleò segretamente con Espero, per colpire Estia. Gravissime ferite le furono inflitte quel giorno, ed ebbe luogo  lo sterminio di *Prinicipati*. Estia pregò allora Potestà e Virtù di unirsi all'esercito di Elìa, per porre fine ai massacri.  Inoltre, portò i cadaveri al dio del Tempo, offrendoli in dono in cambio di un patto, verrà noto come [[il patto di morte perpetua di Estia]]. Ovviamente ne seguì un'ultima alleanza tra Espero e Allumi. Ma Ya'dhal profetizzò ad Estia che ne sarebbe risultato il massacro di tutti gli angeli. Allora Estia riscosse un favore alla dea Selune, che fu responsabile quel giorno del massacro di Cherubini e Dominazioni. Da quel giorno Selune potè illuminare la Luna, col sangue di molti angeli avanzato dalla guerra.

### ### Poema delle Guerre degli Angeli

Sulle rocche del Sole, in vetta allo cielo,  
dimorano gli Angeli, che riluce a fiame,  
custodi d'etterno e divino zelo.

Fu Elios, del Sole iddìo e delle brame,  
a forgiar Serafin, foco, ali e gloria,  
draconi che legan Terra all'alto reame.

Con palchi d'avorio e ossa d'istoria,  
Eraphiel, Auriel, maestà infinita,  
riflettevan del Sol'a fulgida memoria.

Ma la pace svanì quale i'stella smarrita:  
nacque contesa fra'iddèi e l'alte schiere,  
super la luce d'un'ombra svanita.

Estia si fè a Principati e Virtù fedele,  
i Troni vegliando i confini remoti,  
e Potestà scrivean n'e'libri preghiere.

Elìa, co' Serafin e l'Arcangeli devoti,  
fece promessa di potenza e creazione,  
per dar forma a nove vite e novi moti.

Estia, a gran dubio, tese'l sua azione:  
cercò l'alleanza con Elios possente,  
ma Elìa  con Espero tramò tradizione.

Quel giorno il sangue tinse terre ardente:  
fu sterminio di Principati senza scampo,  
mentre Cherubini morivan per mano potente.

Selune, dea della notte e del lampo,  
ricevette da Estia il patto di sangue eterno,  
donde il chiaror lunare ha un rosso campo.

Le corde vocali dei Principati in grembo  
Heluvian raccolse, dio del tempo e del fato,  
per tessere un canto che rompe l'inverno.

Nella guerra finale, l'astro fu macchiato:  
Virtù e Potestà donaron lor' essenza,  
mentre i Dominatori giacevan obliterato.

Eppur, dal caos e dalla sua incandescenza,  
un nuovo equilibrio sbocciò dal dolore,  
tra gli dei e le schiere, eterna sentenza.

Così cantano gli angeli, di guerra e furore,  
sulle Rocche del Sole, celeste dimora,  
sperando che pace prevalga nel cuore.