---
title: "Lista completa dei Metalli"
search: false
format:
  html:
    theme: default
---

### Metalli primari 

-   **Oricalco:** esso conia l'essenza della magia, esso si inseri e fuse con tutti i metalli. Loricalco è presente allo stato della materia noto come Etereo (Mana). La maggior parte dell'Oricalco è mantenuto nel piano etereo. Quando si usa la magia, si incanalano i metalli in una direzione. Il metallo più flessibile è questo, ed è anche quello in grado di legarsi e manipolare più velocemente ed efficaciemente gli altri, pertanto è detto metallo della magia. Questo è noto con molti nomi: essenza magica, fluido di Mistrya, energia magica, o Mana. L'oricalco risponde a un pensiero magico, basato su una precisa sintassi, la detta Lingua degli [[Dèi]].

Utilizzando la [[Lingua degli dei]] è possibile per una persona utilizzare la Magia. Per farlo deve attingere a riserve di Oricalco che derivano dal Cielo. Se una persona è in grado di storare la quantità di informazioni necessarie e tollerare di esdsere usato come una sorta di antenna per il passaggio dell'Oricalco, allora esso si libera dalla mente del caster per produrre effetti molto forti sul mondo.

Esso è infatti in grado di manipolare gli altri [[Elenco Metalli]] in modi molto forti. L'Oricalco è una delle forme energetiche più potenti che esistano, molto al di là delle forme energetiche presenti all'interno del [[Pavranio]]. Si chiama anche Metallo del Comando perché è in grado di muovere gli altri. Un nome appropriato per la magia infatti è anche "Magnetismo Arcano"

-   **Miasma**: il miasma è una versione dell'Oricalco. Come se fosse un colore, una variazione. Probabilmente una sorta di versione arrugginita o distorta dell'oricalco.

Chi ne viene a contatto testimonia una caratteristica del Miasma cioè quella di attaccarsi in modo molto più instabile alle cose. Come se parassitasse le cose, come se le consumasse una volta che vi si fosse attaccato.

Se non si è studiato in modo approfondito l'Occulto, per altro, il miasma viene facilmente scambiato per Oricalco comune.

Le fonti che solitamente fanno uso di Miasma sono: 

- La maggior parte dei Celestiali 
- La magia di Indra e Vengra 
- La magia dei Tiefling di alto livello

La sola presenza di grandi quantità di Miasma è in grado di alterare in modi strani e macabri il tessuto del mondo. Luoghi esposti a questo tipo di magia potrebbero essere vittima di strane piaghe, distorsioni della percezione del mondo o delle leggi della natura.

-   **Irradion**: il metallo della tonalità, della musica. Si tratta del metallo che dona la musicalità alla Lingua degli dei Esso dona un senso alle cose, il loro normale fluire è descritto da esso come se per la lingua  lui fosse l’intonazione, solo la  runa [[Ansuz]], sua maestà Sintassi e grammatica, gli è superiore. Ma è questo il metallo che consente la musicalità della [[Lingua degli dei]] e delle [[Rune]], pertanto l'uso preintuitivo delle rune è dovuto all'Irradion.

Anche se i Bardi possono come si dice *bendare*, cioè muoverlo per porre delle modifiche al reale (minimali come muovere una foglia, aprire una finestra, o cose così, oltre che usare la capacità di Metadialogo dei bardi) Non viene considerato al pari realmente dell’ [[Oricalco]] per l’impatto che ha.

Noto come il metallo dei Bardi, l'Irradion viene visto dai bardi con delle prove che scalano su Carisma. Il Bardo è in grado di vederlo in tutta la struttura del mondo, e dove esso è silenzioso significa che c'è stata una manipolazione da parte della runa Ansuz, anche se quasi nessuno conosce le rune al punto da poterlo dire.

Bardi esperti possono anche arrivare a capire a seconda del suono che l'irradion fa se ci sia stata della magia o l'intervento di un dio. Ma è una cosa molto sottile e difficile.

-   **Pavranio**: esso conia l'essenza delle ossa, da esso si originò la roccia come la conosciamo, ed era il più presente.

-   **Rame**: un materiale in grado facilmente di unire Pavranio e Giada, ma facilmente deperibile. Tutto ciò che è fatto con il Rame è pertanto mortale.

-   **Giada**: elemento della Volontà, è ciò che fonda la vita come intenzione. Ciò che rende la vita è merito della Giada. Quando si riesce a legare ad altri metalli efficaciemente, essa genera un metallo detto **Noema**: questo metallo è come se fosse una sorta di risultante, ogni Noema è a sè, come se esistesse solo in quella particolare configurazione. Inoltre, il Noema si organizza in spirali contorte che conservano l'identità del Noema stesso. Piccole bolle di questo Noema sono i ricordi.

-   **Icore (Dei)** = Giada + Oricalco insieme danno vita a magia con della volontà, fondando pertanto gli dèi. L'Icore è altrimenti detto il sangue degli dèi, il noema degli dèi si chiama Icore, ed è un metallo estremamente stabile.

-   **Ladega**: lega insieme, serve a legare un oggetto o luogo a una fonte di magia, come nei seguenti casi
    - Sacralità: ogni luogo/oggetto/soggetto che sia sacro a un altro, o ad una divinità, lo è grazie alla Ladega. Un esempio sono i Talismani o i [Beniamini](/capitoli/Regole/meccaniche_nascoste/beniamino.qmd)
    - Contratti: Le firme dei patti di Indra sono intrise di Ladega

-   **Edenia**: il metallo del piacere.

-   **Algheina**: il metallo del dolore. Funge da base per l'[[Arte dei tatuaggi]].

-   **Taddìma**: il metallo dell'ascendenza, del comando e del controllo. Funge da base all'[[Arte Vodoo]]

-   **Cronomia** metallo del tempo 

-   **Humja**: un metallo che riguarda l’umanità, rende umani. Rende in grado di amare, di provare compamssione. È l’elemento che è legato alle rune sociali, e probabilmente quello che va affievolendosi nei tiefling.

### **Metalli di Battaglia**

-   **Tungsteno**: *Ira del Titano.* Questo elemento distrugge scomponendo lentamente con la forza del calore. Assimilabile al fuoco, ma non propriamente fuoco, è solo una delle sue manifestazioni. Questo elemento fu inserito ai tempi della creazione dei Draghi

-   **Titanio**: *Essenza del Vuoto:* questo elemento rallenta, ferma, immobilizza, raffredda. Assimilabile al freddo.

-   **Argento** : *Odio degli Angeli*: questo elemento rappresenta il desiderio di morte. Attacca direttamente il Sangue quando viene a contatto con una forma vitale, consumandolo. *Odio degli Angeli*: questo elemento rappresenta il desiderio di morte. Attacca direttamente il Sangue quando viene a contatto con una forma vitale, consumandolo. L'argento normale ha una residuale di questo elemento al suo interno, e non è un caso che i Vampiri ne sia deboli.

L'argento bianco è una sua deriva.

-   **Boro**: *Sonata Demoniaca*: questo elemento costituisce una forma di vibrazione sonora.

-   **Platino**: *Panico Primordiale:* è una forza in grado di spostare, da vedere come una pressione, la prima reazione che porta un riflesso ad attivarsi, prima ancora di avere paura.

-   **Neon:** *Precipitato del Cielo:* questo elemento costituisce un’essenza molto eterea L'utilizzo magico di questo metallo, tramite l' Oricalco che tutto governa, infatti, è possibile utilizzarlo per spostarsi nello spazio, muovere le cose. i poteri di Telecinesi, chi li ha almeno, provengono dall'utilizzo del Neon.

Le Fate sono esseri composti dall'unione del neon, oricalco, e ovviamente una punta di Giada.

**A partire** da questi metalli, è stato creato un nuovo tipo di magia dagli [Incantatori della nuova era](/capitoli/Regole/Classi%20Nascoste/mago_guerra.html)

### Metalli da Forgia

-   **Meteorite**: Le armi in meteorite hanno una serie di particolarità

    - Particolare abilità perforante (sono infatti usate dai Cacciatori di draghi e alla base delle Armi da fuoco)
    - Non hanno molta resistenza agli incantamenti, pertanto possono tollerare fino a 3 incantamenti che vengono sovrapposti, senza possibilità di fallimento.
    - Possono legarsi alla Giada del propietario, facendo in modo di volare nella direzione del propietario se questo lo desidera.

-   **Osso di Drago**: Armi costruite in osso di Draghi, se prese dalla Carcassa di un Dragone, almeno, hanno la straordinaria capacità di assorbire le sostanze naturali.

    - Non può essere incantata
    - Può essere infusa con 4 veleni se di "Dragone", 6 veleni se di "masto Dragone", e numero illimato se di "Procura Drago"

-   **Ametista**: Metallo con cui i Monaci fondano le loro armi. Le armi in Ametista si muovono inoltre secondo l'istinto Marziale del loro possessore, non richiedendo dunque una particolare abilità nellusarli, serve solo un istinto profondamente radicato nell'animo di chi lo usa nel combattere.

    - Un'arma in Ametista non può essere distrutta
    - Particolarmente adatta a essere infusa e incantata, ma di solito i monaci vietano questa pratica.
    - Un materiale molto reattivo alla magia anche di bassa frequenza, si adatta bene a tutte le tecniche dei monaci.

-   **Argento Bianco**: L'argento Bianco è un materiale a base argento ( quindi un sottoprodotto del Pavranio come tutti i metalli) infuso col sangue degli angeli. Queste armi hanno la proprietà di poter colpire

    -   gli Dèi, anche se si tratterebbe di una mossa suicida,
    -   i Mannari più come effetto collaterale che voluto,
    -   i Tiefling visti inizialmente come servitori degli dei della Luna.
    -   I Banshee

    Una nota dolente riguarda la quanità. Sono state forgiate intorno alle 300 spade in oro bianco, ma non è stato concesso altro sangue dagli angeli, pertanto non è stato possibile crearne di nuove.

    -   Un'arma in argento bianco non può essere danneggiata in alcun modo.
    -   L'argento bianco ha come altra caratteristica notevole quella di lasciarsi incantare con molta facilità, offrendo poca se non nulla resistenza ai sovraincantamenti senza alcun limite.

-   **Avorio dei Giganti**: Avorio dei Giganti è il metallo che si estrae dalla Carcassa di un Gigante "Raffinato" o "Puro". Se estratto da un "Lavorato", può essere migliorato con un pesante processo di un Fabbro Magicante, se esce vivo dal quale (fallimento 1d4) potrà considerarsi Avorio dei Giganti.

    Condividono le seguenti caratteristiche

    -   Le armi sono indistruttibili
    -   Le armi provocano il rispetto da parte di Giganti di livello inferiore a quello a cui è stato estratto l'arma, e ostilità da quelli di livello uguale e superiore.
    -   Le armi possiedono svariate capacità a seconda dei metalli che il Gigante aveva esaurito quando aveva creato la propria struttura ossea.

-   **Diasprite** Un metallo rosso cremisi intenso, si ottiene solo nelle secche di alcune isole molto remote dell Mare dei Tesori, portato a riva dal Vetro Sale. Giunge nelle forme di una conchiglia viola intenso, e se raffinato otteniamo la Diasprite. La Diasprite è un metallo particolare, in grado di legare bene solo con il Miasma. Quando si prova a incantare la Diasprite con dell'Oricalco, si fanno solamente dei danni, si rompe la spada:

    - Le armi non possono essere incantate con magia a base di Oricalco
    - Le armi possono essere incantate con magia a base di Miasma (gli incantatori che sanno usarla sono molto rari)
    - Se si riversa Miasma puro, o materiale che lo contiene sulla spada (cosa molto difficile da ottenere), essa lo beve, e acquisisce delle capacità che sono proprie della, almeno così dicono i magicanti, conchiglia di riferimento che l'ha partorito.

-   **Osso di Balena Bianca**: Questo rarissimo materiale è usato (più facilmente trasmutato) per generare armi da mago. Le armi fatte con questo materiale sono capaci di canalizzare la magia dell'incantatore in un modo molto particolare, legandosi alla sua capacità di manipolare l'Oricalco Il caster che impugna quest'arma fa danno tagliente pari a Intelligenza. Usa Intelligenza per colpire e difendere al posto di Destrezza.

-   Il Quarzo trattiene l’Oricalco 
-   Diamanti o Carbone trattengono il Rame.
