---
title: "Lore dei Pirati e dei Mari"
format:
  html:
    theme: default
---

### Il Mare 

Il mare è una distesa di acqua non regolata da nessun governo, piena di insiedie e pericoli di tutti i tipi che potete immaginare in un mare fantasy. 

La sola forma di regolamentazione è rappresentata da una serie di commpagnie che si occupano delle tratte. Sono istitutioni di traffico proettete e più costose. Viaggiano spesso su richiesta di regni importanti o personaggi ricchi, perché sanno difendersi bene. Si tratta di distinti signori in giro per affari, non certamente di santi, ma comunque sono affidabili.
Le loro navi conservano spesso l'iscrizione della runa Laguz, pertanto sono di altissimo valore. 

-  Compagnia Tambourin 
-  Compagnia Jameson 

All'opposto, ovviamente esistono le Bandiere Pirata. E tendono ad essere piuttoswto pericolose. 
Le tre Bandiere dei Pirati Nobili famose sono 

- Jack Laverna 
- Roberts Talisker
- Vera Reale

Queste dominano i mari in modo incontrastato. Sono bandiere che vengono usate anche per fare paura anche se non sono loro i portatori della bandiera. Nel senso non sei Jack Averna ma la usi magari. Il rischio è che incroci una nave della flotta di Averna sei fottuto.  

Di Mari ne esistono 4

#### Il Mare Glaciale 

Mare aspro, difficile da navigare, spesso ghiacciato. Territorio di pertinenza legato soprattutto alla dea Bora. 

#### Oltracque 

Un mare che si dice sia vuoto, non si trova niente in quel mare, più ci si allontana dalla costa più diminuisce l'interesse per quelle acque.

#### La Manica

Il più ricco ed utilizzato per gli scambi commerciali per sè.  Anche quello in cui è più forte la mano delle compagnie Jameson e Tambourin. Non eccessivamente pericoloso. Tra tutti forse il mare più sicuro in cui navigare, più noto e meno invaso di pirati.

#### Il Mare dei Tesori

Un mare selvaggio, pieno di pirati. Il commercio è avido dei tesori portati dal mare stesso. Il mare gorgoglia, frizzante e spumoso di una sostanza misteriosa, la Vetrsale. Come se il mare fosse vivo, si muove, portando nuove correnti, e soprattutto portando dal fondale tesori. Non si sa se siano tesori antichi, ma alcuni sospettano siano di altre civiltà. O che arrivino da oltre le isole note, nel posto chiamato Thalassa. Nessuno ha mai segnato l'ultimo scoglio dell'arcipelago del mare dei tesori, e non si sa quanto in òà si spinga. 

##### Vetrosale

La Vetrosale può essere raccolta. Raccogliendo quantità  veramente ampie di acqua del mare dei tesori, facendo evaporare l'acqua si otteine questo sale molto duro. Lavorato a dovere con l'acquaforte viene poi resa una sostanza viscosa. Questa sostanza viscosa ha un atlissimo valore commerciale. Una fiala si vende alle persone giuste a 2500 kilia. Viene pertanto usata come garanzia in molti casi. 

Si sa che gettando a mare il suo contenuto si alzerà una corrente dal fondale con buona probabilità. Questo, se sul fondale ci fosse qualcosa di prezioso, porterà a farlo riemergere. Per questo si dice che alcuni pirati abbiano nascosto alcuni tesori proprio in mare, dove è più difficile localizzarli. 

Una nota particolare: è risaputo che la vetrosale abbia molti più usi di così, ma  non si sa quali. I pirati nobili sanno cosa farsene ad esempio sicuramente, si dice anche che Jack Laverna se la beva. 