---
title: "Rune"
format:
  html:
    theme: default
---

# Rune


Nessun tipo di giocatore può vantare conoscienza sulle rune. Forse un venti nat può darti o il nome o la forma della runa, ma non c'è giocatore che le possa conoscere, cosituiscono un mistero persino per gli dèi. 

Donare una runa a una Divinità può significare distruggere l'equilibrio delle forze del cosmo. 

##### Origine

 Le rune sono antiche, sono l’estratto del mondo. In origine erano migliaia di Rune, ora ne avanzano 24, pochissime, custodite con gelosia nel mondo da quelli che le possiedono. Offrono un potere immenso sulla realtà, conoscendola. Gli \[\[Dèi\]\] la conoscono in modo preintuitivo, ma ono conoscendo tutte le rune, hanno sviluppato un linguaggio sceritto noto come \[\[Linguaggio arcano\]\]  con cui utilizzano la Lingua degli dèo, che sarebbe invece basata sulle rune, in scioltezza. Ma non con la massima autorità possibile. Pertanto non possono rscrivere completamente il mondo.

utilizzando le rune in modo preintuitivo è possibile fare grandi magie.

###### Donate dagli dèi

Un dio che abbia una conoscenza completa della runa, può donarla agli umoini, i quali, se gli va bene, possono averna una conoscenza preintuitiva.

##### *Magia?*

Le rune costituiscono i binari che regolano il rapporto tra il mondo e ciò che lo abita. Le rune non sono propriamente magia. O dipende da cosa intendiamo noi con magia. Se con magia intendiamo ciò che si muove tramite l’Oricalco, allora non è magia. La magia è semplicemente ciò che non si spiega per chi non è istruito. Se la magia originata dall’Oricalco è una forza, le rune sono il piano ove questa magia può muoversi. Chi possiede molta magia può avere la forza di sollevare un sasso sopra la terra, ma le rune ordinano al mondo che una volta lasciato il sasso, questo ricada sulla terra. I binari primitivi che spiegano il mondo com’è. Se solo conoscessimo tutte le rune, potremmo forse spiegarci tutto. Chi usa le rune non immette un potere in sé stesso per poi emetterla in qualche forma, semplicemente spiega al reale come comportarsi, ed esso come tale si comporta.

##### Utilizzare una runa.

-   Mancato utilizzo: conoscere il nome della runa certo avvicina, o comunque aiuta le ricerche, ma da sola è inservibile.
-   Utilizzo implicito: Una runa viene usata, semplicemente, in quanto linguaggio: si manifesta nei suoi contesti d’uso. Un parallelismo che può aiutare è con la spada. Solo conoscere il nome di una runa è qualcosa, ma non di più che se fornissi una definizione di spada: “una lama di ferro, tipicamente acciaio, trattato per riuscire a ferire, tipicamente di taglio, composto da un’impugnatura detta elsa, una guardia che la delimita, e una lama.” La differenza tra conoscerla e non conoscere effettivamente aiuta: chi guarda una spada senza sapere cose sia potrebbe pensare di ballarci sopra la macumba, mentre un alieno venuto dallo spazio avendo questa definizione almeno farebbe la grazia di prenderla per l’impugnatura e provare a rotearla goffamente contro un nemico. Ma un esperto schermidore sa *usare* una spada. Significa che sa come impugnarla, le varie tecniche di difesa e offesa, le barie posizioni, che tipi di spade ci sono e come cambia lo stile di combattimento, come cambia in base al contesto o all’arma dell’avversario, poi sa come mantenerla nel tempo, e così via, e tutto questo con, a vedersi, innata scioltezza. Nelle sue mani, nei suoi contesti d’uso, si manifesta la spada oltre la mera e vuota definizione di spada. Chi ne fa un utilizzo implicito sono tutti quelli che applicano la magia delle rune in modo spontaneo, tipo i Bardi quando utilizzano l'Irradion.

In sintesi: \*\*Conoscere implicitamente una runa, in pratica, significa poter eseguire magie nel contesto semantico della runa senza essere limitati da una sola frase. Se conosci la runa del "vento" puoi esdeguire magie del "vento" con tutta la flessibilità del mondo.

-   Utilizzo esplicito: Allo stesso modo chi ha studiato una runa, visto e applicato una runa nei suoi contesti d’uso, conoscendo il linguaggio, perché di questo si parla, allora questi solo dicendola sarà in grado di usarla, la runa sarà strumento di chi la conoscerà. Coi limiti imposti alla runa che solo chi la conosce riesce a immaginare. Così come chi non si intende di spade difficilmente penserà che questa dovrebbe essere in grado di piegarsi come una molla per poter funzionare al meglio, invece di essere rigida come la roccia, allo stesso modo le rune hanno limiti che conosce solo chi le padroneggia. Conoscere la runa e saperla usare èè un potere immenso, non si è limitati all'uso implicito, solo che nemmeno gli dèi ce la fanno, pertanto è più che altro un sogno. Anche gli uomini sono limitati ad un uso preintuitivo, come segue alla voce "Donate dagli dèi". Non si parla di conoscere semplicemente il nome, e di cosa allora? Boh, nemmeno gli dèi l'hanno capito veramente... Tu sapresti dirmi chi ti ha insegnato il significato esplicito di "casa"? Quello è il problema.

Così una volta nota, la runa viene semplicemente tracciata. Un magicante decide solitamente se questa runa sia o meno visibile ai mortali, ma spesso decide di no, poiché meno sono le rune note, meglio è.

###### *Insegnare*

Una runa non è una cosa per tutti. Come essere un buon schermidore non rende un gran maestro di scherma, anche passare la conoscenza delle rune è estremamente ostico. Uno potrebbe essere il più grande mago runico eppure non riuscire ad insegnare nemmeno la più semplice.

C’è inoltre qualcosa delle rune che tende a sfuggire. Anche solo il nome di una runa è qualcosa che tende a svanire nella memoria di chi ascolta. È facile che dopo un paio di giorni anche se lo si è ripetuto più volte, si dimentichi o il grafema o il fonema della runa, questo ad amplificare il mistero che sottende questo tipo di magia. \###### *Difficoltà* Di apprendimento dice quanti sono i contesti d’uso, e quindi quanto occorre prima di padroneggiare la runa. Ci si lasci catturare più che altro dalla suggestività di questa descrizione, poiché non è così semplice descrivere qualcosa delle rune a chi non le consoce. La classificazione come segue:

-        1: Come apprendere una lingua a ideogrammi da anziano cresciuto coi lupi

-        2: Come apprende una lingua a fonemi da sordo

-        3: Come apprendere il linguaggio dei segni da cieco

###### *Rarità*

Della runa dice quanto è nota la runa alla gente. Ci si lasci catturare più che altro dalla suggestività di questa descrizione, poiché non è così semplice descrivere qualcosa delle rune a chi non le consoce. Per semplicità si considera una regione dove vivono 1 milione di abitanti, dunque una vasta regione. La possibilità di ottenere da loro questa informazione senza sapere che sono loro a saperla

- 1: solo tre vecchi, ognuno di essi vive nascosto in una grotta, ed è scontroso con chiunque
- 2: 100 dotti, in librerie o scuole, che le considerano delle sciocchezze da ragazzini
- 3: 1000 trovatori, musici o cantastorie, che confondono tra loro le storie al riguardo, quindi spesso inventano.

###### *Reazione*

Le rune reagiscono al caldo e al freddo, tranne due sole rune, che non è né l’una né l’altra, Laguz e Ansuz. Quando una runa del fuoco si trova in un ambiente caldo riesce nel suo scopo con più facilità, quando si trova in ambiente freddo con più difficoltà. E viceversa. Gli oggetti o i portatori di una runa subiscono una variazione termica determinata dalla runa.

###### *Conflitto*

\*Quando due rune confliggono, cioè quando prevedono effetti opposti tra di loro, ci si rifà alla gerarchia, cioè all’ordine con cui compaiono queste rune in questo libro, che ne descrive la priorità, con una eccezione: tra Fehu e Isa non c’è asimmetria.

###### *Combinazione*

È possibile combinare due rune tra loro. Se però il significato di una runa da sola è difficile da spiegare non ci metteremo in questa sede a spiegare il significato combinato di più rune, stia all’abilità dei magicanti.

Le rune vengono divise secondo la seguente gerarchia

### 1)     Rune dell’Ordine

Rappresentano la tensione ordinata che mantiene in equilibrio la tensione tra Sole e Luna, le due forze che mantengono il mondo tra il Caos e il Vuoto.

Ansuz, il codice delle rune. Probabilmente da questa runa originarono tutte le altre. Né calda, né fredda. Conoscendo Ansuz è possibile negare ogni runa, bloccare la validità di ogni runa, ripristinarla, è possibile conoscere ogni runa solo imparandone il nome. Ansuz consente di vedere, di sapere. Ansuz consente di vedere i fili del linguaggio che intrecciano la realtà: ogni magia di ogni tipo viene svelata (a eccezione della magia delle erbe, poiché essa non prevede linguaggio). I maghi che conoscono questa runa possono decifrare ogni codice personale di ogni mago, possono leggere gli incantesimi nel loro codice primo.

Difficoltà di apprendimento

-        Rarità: 1 -        Difficolta 1 (richieste almeno altre 5 rune)

Dagaz, *fuoco*, il tramonto che è alba. Questa runa unisce tra di loro i \[\[Elenco Metalli\]\] primordiali a creare ogni sostanza pluri elementale. Dagaz è incisa su ogni uomo, che è formato infatti da Pavranio, Sangue e Oricalco in minime dosi. È incisa su ogni Dio, l’Icore è infatti Giada e Oricalco, e così via. È possibile, almeno tecnicamente con Dagaz scomporre queste essenze, a patto di rompere la runa che le unisce. Rompere una runa è cosa complessa anche per chi conosce Dagaz. Sempre con Dagaz è possibile convertire un elemento in un altro, poiché il tramonto è alba, quando i confini si uniscono.

-        Difficoltà: 2 -        Rarità: 1

Naudhiz, *ghiaccio*, frizione del fato. La runa che impone di *imbattersi sul proprio destino sulla strada presa per evitarlo.* Chi è in possesso di questa runa spesso è un profeta, o un oracolo. Le profezie sono tali perché recitate tramite Naudhiz, così che ogni sforzo compiuto dal soggetto che la riceve per liberarsi dal suo destino, non fa altro che legarlo ancora di più ad esso. Il legame più potente di questa runa è con l' \[\[Irradion\]\]. Il Grande bardo Eril una volta disse "La frizionie di Naudhiz genera le note dell'Irradion"

-        Difficoltà: 2 -        Rarità:1

Raidho, *fuoco*, la ruota che viaggia. Questa runa è in grado di generare cerchi nel tempo, atti a ripristinare un ordine perduto. Cosa significhi ordine perduto è chiaro solo a chi la runa la conosce, altra linea sottile che pertiene all’interpretazione delle rune.

-        Difficoltà: 1 -        Rarità: 1

Jera, *fuoco*, profezia del manifesto. Jera è la runa che implica il funzionamento manifesto delle rune stesse, poiché essa è il manifestarsi del reale nelle sue qualità costitutive. Jera è una runa che si autogenera, fonda se stessa nell’autonomia che si realizza del mondo. Un guerriero che combattesse abilmente con una spada, sempre con lo stesso spirito, con lo stesso codice, compirebbe il destino della spada al punto che Jera potrebbe apparire sulla spada legandoli, rafforzando quel destino. Un povero violinista che sbagliasse sempre la solita nota col suo strumento è in questo che è legato forse dopo un po’: Jera impone il manifestarsi del suo destino, come una maledizione. Pertanto non è possibile imporre Jera, anche se per vederla è necessario studiarla.

-        Difficoltà: 3

Ehiwaz, *fuoco*, asse tra i mondi.  Ehiwaz è in grado di fare muovere tra i mondi. Certi ordini monastici ne fanno un uso implicito proiettandosi nel piano astrale, solo uno dei piani, come chi non sa di saper nuotare perché ha imparato da bambino: non si muoverà libero nella tempesta come un atleta,  ma certo galleggerà e se gli fosse richiesto di raggiungere un punto lo potrebbe anche fare. Tale è Ehiwaz: conoscere la tecnica del nuoto fino in fondo e spostarsi a piacimento.

-        Difficoltà: 2 -        Rarità: 2

### 2)     Rune di Eris

Le forze che rappresentano il Caos e il Vuoto, le due entità da un lato e dall’altra del nostro mondo.

Isa, *ghiaccio*, l’esaurirsi. Isa consuma il mondo per evitare che si sgretoli. Il seme della morte è contenuto in qualcosa che chiede di non frantumarsi. Una runa molto pericolosa da apprendere, più che semplicemente complessa: molti rischiano di trovarsi pietrificati male interpretandone il significato.  Una persona che decidesse di usarla su di sé potrebbe dirsi forte, forse invulnerabile, nei suoi obbiettivi… nei realisticamente 7 giorni in cui il suo fisico riuscisse a tollerare la runa.

-        Difficoltà: 2 NB pericolo -        Rarità: 2

Fehu, *fuoco*, il moltiplicarsi. Fehu è una forza che spinge tutto ciò che è positivo, tutte le forze che mirano al moltiplicarsi delle stesse, a espandersi. Un incendio ne trarrebbe giovamento, così come il commercio di un mercante, così come le fertilità degli animali nel periodo dell’accoppiamento. La sola disgrazia dei Fehu è che non bada a come genera, ma genera.

-        Difficoltà: 2 -        Rarità: 3

Uruz, *ghiaccio*, liberare la vita. Uruz scioglie la vita che è contenuta chiusa in una potenza. Una runa dagli impieghi o estremi o ridicoli: si potrebbe fare schiudere un pulcino da un uovo, fare germogliare un fiore che si rifiuta di uscire, o facilitare un parto che si rifiuta di compiersi. Ma si potrebbe usare insieme ad Hagalaz: dove Hagalaz ha contenuto, Uruz ha liberato. Antichi manufatti vengono conservati nelle loro proprietà, bloccandone la magia. Lo scorrere del tempo in un luogo può fermarsi e niente evolversi per degli organismi grazie ad Hagalaz, e fatti ripartire grazie a Uruz. L’effetto di alcune rune può essere bloccato grazie ad Hagalaz e trovare nuova forma grazie a Uruz. Antiche creature adeguatamente trattate e poi bloccate grazie ad Hagalaz potrebbero rinascere con Uruz. La dea \[\[Estia\]\] è l'unica tra le dee a farne un grande uso.

-        Difficoltà: 3 -        Rarità: 2

Hagalaz, *ghiaccio*, preservare la vita. Una runa che trova la  sua utilità meglio descritta insieme ad Uruz:  dove Hagalaz ha contenuto, Uruz ha liberato. Antichi manufatti vengono conservati nelle loro proprietà, bloccandone la magia. Lo scorrere del tempo in un luogo può fermarsi e niente evolversi per degli organismi grazie ad Hagalaz, e fatti ripartire grazie a Uruz. L’effetto di alcune rune può essere bloccato grazie ad Hagalaz e trovare nuova forma grazie a Uruz. Antiche creature adeguatamente trattate e poi bloccate grazie ad Hagalaz potrebbero rinascere con Uruz. La dea \[\[Estia\]\] è l'unica tra le dee a farne un grande uso.

-        Difficoltà: 3 -        Rarità: 2

Pertrho, *fuoco*, gli estremi del caso. Questa runa è ciò che è caso. I suoi usi sono molto ambigui e misteriosi. Si sa che c’è chi è riuscita a usarla su una porta di modo che questa porta una volta aperta portasse su una stanza casuale del mondo per chi la runa la conoscesse. I mille modi di Pertrho non sono chiari, e forse questo dipende appunto da Pertho stesso.

-        Difficoltà: 2 -        Rarità: 2

### 3)     Rune della civiltà

Le rune che derivano dal Rame, che rappresentano il Rame ed il sangue che lo include.

Mannaz, *fuoco*, antropafflato. Mannaz dona la facoltà umana a un oggetto o un animale che la contiene. Ciò che il magicante intende come massima qualità dell’uomo viene trasferito, animando ciò su cui viene applicato. Un uso pittoresco, al limite dello stupido, di questa runa prevederebbe di animare delle scope per pulire una casa, ma non si pensa possa accadere.  Invece dare Mannaz su di un lupo lo porterebbe ad agire come la massima rappresentazione di uomo secondo chi ha applicato la runa, di essere dotato di vita. In quanto tale, si ritiene che Mannaz sia la runa della Giada, dell’elemento della volontà. Si ritiene che le due cose siano sovrapposte al punto che la Giada non sia altro che la manifestazione della Giada, e che dove Mannaz  è incisa, la Giada necessariamente è.  Tuttavia i risultati dell’applicazione di questa runa tendono ad essere inquietanti e sinistri a volte, poiché questo lupo, per quanto dotato di volontà, non per forza ha una società a cui appartiene, e se la fondasse non sarebbe uguale alla nostra, e quindi i suoi comportamenti non sarebbero di facile itelleggibilità.

-        Difficoltà: 1 -        Rarità: 2

Othala, *fuoco*, sangue della tribù. Othala è una runa impilicitamente usata da tutte quelle tribù che celebrano il passaggio alla vita adulta grazie a un rituale che trasmette un qualche potrere da antenati a un giovane adulto, con il fine che questi poi la protegga. Chi conosce questa runa è in grado di passare alla propria progenie capacità che siano in grado di proteggere il resto della progenie. Il limite è che questo potrebbe accadere solo quando questi fosse intenzionato ad usarle per proteggere la progenie, o al contrario ricevendole lo diventerebbe, e porterebbe un terribile fardello se li abbandonasse.

-        Difficoltà: 3 -        Rarità: 2

Tiwaz, *ghiaccio*, egemonia del sovrano. Questa antichissima runa consentiva di emanare la giustizia. Ahinoi, per un gioco sofistico, la giustizia *è* quanto Tiwaz impone che sia. La qualità di poteri garantiti a chi consce questa runa consente di diventare tanto un grande sovrano quanto un tiranno, poiché chi possiede Tiwaz *fonda, manifesta* la giustizia, e chi la vede manifestarsi avverte l’autorità che emana, e si relaziona all’infrangerla con lo stesso animo di chi viola scientemente regole che sanno mandare avanti la società. (In Segreto, il potere del re di \[\[Klessa\|Mistral\]\], \[\[Sarman\]\], deriva da questa runa)

-        Difficoltà: 2 -        Rarità: 1

Kenaz, *fuoco*, creare con estro. Questa runa fonda gli artigiani. Un fuoco domesticato sul cui braciere venisse incisa questa runa consente di creare quanto è possibile creare col fuoco, solo estendendo al fuoco le componenti necessarie alla sua creazione. La semplicità di questa runa è il fondamento della sua salvezza: esistono altari fondati da \[\[Estia\]\], dea del rifiugio, su cui è incisa questa runa, e molti viaggiatori ne traggono conforto.

-        Difficoltà: 2 -        Rarità: 3

Wunjo, *fuoco*, l’armonia dei fratelli. Una runa che rende gli uomini in grado di condividere lo stesso spirito, come se appartenessero allo stesso sangue. La dote che vorresti per ogni diplomatico, ogni capo militare o cittandino, ogni prete, ogni qual che si voglia: la scioltezza e serenità delle interazioni sociali quando questa runa viene manifestata supera ogni umana reale empatia e simpatia.

-        Difficoltà: 3 -        Rarit: 2

Ehwaz, *fuoco*, dove sono il cavallo e il cavaliere. Il legame che unisce in uno spirito che agisce, che combatte, sostenendosi, sostenendo insieme una battaglia. Il legame che definisce un cacciatore legato al proprio animale, per il quale riesce a condividerne i pensieri, gli intenti, i sensi. \[\[Dèi#Selune\|Selune\]\] ancora in grado di tracciarla, legandola ai cacciatori più meritevoli. Il legame che renderebbe forte un cavallo col suo cavaliere, un cavaliere col suo scudiero. Ma solo un duo, non c’è terzo i questa runa.

-         Difficoltà: 3 -        Rarità: 3

###### 4)     Rune Divine

Le rune che descrivono il legame tra il Sangue e l’Icore. I sacerdoti spesso vengono istruiti sull’uso di queste rune, salvo eccezione per l’ultima.

Berkano, *fuoco*, custode dei deboli. Dove nasce una betulla qui questa runa è stata tracciata: il rifugio dei deboli, che \[\[Estia\]\] ha manifestato spesso nei luoghi più pericolosi, inizialmente mossa a pietà alla vista di una puerpera in fuga dai nemici. Le rune Berkano non solo vengono tracciate, ma solitamente vengono anche segnate per essere rese note a chi non vede le rune, che lì c’è un rifugio. Ed è un’oscenità senza costume, come tradire la tregua data da un negoziato di guerra, scrivere a vuoto Berkano da qualche parte.

-        Difficoltà: 3 -        Rarità: 2

Gebo, *ghiaccio*, vincolare i legami. Una runa che è stata presa in ostaggio da \[\[Dèi#Indra\|Indra\]\], la dea dei patti.  Spesso acccade che un oggetto d’uso prenda una piega inaspettata, che un simbolo non possa essere visto che in un certo modo per l’uso che qualcuno ne ha fatto. Scoperti i fuochi d’artificio, non si può fare a meno di creare i cannoni. Tale è stato il destino di questa runa: i saggi del passato ci informano che Gebo è probabilmente di più di quanto siamo abituati a pensare, tanto che a volte sorge spontanea in certi legami. Tra ospiti a volte sorge, raramente, Gebo, legando i due in un vincolo solidale che li lega tra generazioni. Purtroppo però è maggiormente impiegata per fare un patto con \[\[Dèi#Indra\|Indra\]\]. La dea richiede questa runa per essere contattata, se non si degna di giungere da sola, un pegno di magia e un contratto, con delle precise condizioni. Per via della deformazione che ne ha fatto la dea, che probabilmente ne ha modificato i contesti d’uso al punto da renderla irriconoscibile, è diventata una condanna che spesso fa presagire patti sconvenienti, tragedie o condanne.

-        Difficoltà: 3 -        Rarità: 3

Ehlaz, *fuoco*, il coraggio di un martire. Questa runa assiste i guerrieri in battaglia, quando questi dimostrano di non temere la morte, di combattere in virtù di altro che non sia la propria sopravvivenza. Il legame con la divinità non è chiarissimo: chi vede le rune riesce a vedere un cigno volare sopra la testa del guerriero in questione, ma non è ben chiaro se sia la manifestazione di un dio oppure no. Molto più plausibilmente invece, la runa è in grado di richiamare l’Oricalco per il guerriero che si batte in questo modo, cioè con forte Volontà, attingendolo dalla fonte più vicina, che probabilmente è un dio, perché fonte più vicina e più densa di Oricalco, senza che sia il dio a concederla. La forma del cigno non è che la raffigurazione visibile, una delle tante, dell’Oricalco.

-        Difficoltà: 3 -        Rarità: 2

Sowilo, *fuoco*, il faro di Dio. Questa runa è solitamente di pertinenza dei sacerdoti. Quando questa runa è accesa, il dio non può ignorare ciò che un uomo sta facendo. Non che debba intervenire per forza, ma è almeno sempre testimone delle sue azioni. La sottigliezza di chi consoce questa runa è scegliere di mostrare alcune cose, ed altre meno. Fu in realtà ricevuta in dono dai seguaci di \[\[Allumi\]\].

-        Difficoltà: 3 -        Rarità: 1

Thurisaz, *fuoco*, il fulmine dei deboli. Questa è la runa che più di tutte descrive un legame di aiuto diretto tra un dio e un uomo. Questa runa incalza il potere di un dio, anche se non sappiamo qale, nella forma del fulmine, del tuono. Il dio assiste l’uomo che scende in battaglia in difesa di qualcosa. Il confine che delimita cosa è aiuto e cosa è attacco sa essere abbastanza sottile.

-        Rarità: 2 -        Difficoltà: 3

Ingwaz, *ghiaccio*, sacrificio degli altari. Runa controversa. L’uso più antico, più primigenio, fu scoperto da alcune streghe. Fonda infatti alla definizione di *megera*. Queste streghe trovano il loro potere da un amplesso con un uomo, il quale ne esce senza vita, e trovandosi puerpere. Il loro feto alimenta la loro magia, concedendo loro Oricalco libero, grande potere anche se instabile. Una deriva più contemporanea ed estesa di questa runa consente di ottenere potere da un sacrificio: su un altare, per esempio, rende possibile estrarre la forza di un individuo, vitale o magica, ma non di convertirla.

-        Difficoltà: 2 -        Rarità: 1

###### 5)     Rune perdute

non si sa da dove abbia origine questa runa.

Laguz, *acqua*, oceano dimenticato. Questa runa ha un chiaro legame con Seltan, dio dei marinai, ed è probabilmente lui ad averla insegnata all’uomo. Seltan usava la runa solamente sulle navi, la nota Flotta di Seltan è quell’insieme di navi benedette da immemore tempo che non hanno mai subito un danno né mancato una consegna, che non necessitano manutenzione e prendono sempre il vento, e fanno dunque la fortuna di chi le possiede. Purtroppo sono diventati pezzi unici, perché il culto del dio è morto da tempo, ed egli, forse offeso, non si è più trovato tra i mortali. Dunque sono in molti a conoscere la raffigurazione, ma per la reale spiegazione della runa è un’altra cosa. Probabilmente rende un oggetto di proprietà del mare, questa è la spiegazione più accurata che gli si è trovata. Nulla di male per una nave, creata per appartenergli, ma quando una spada finisce di proprietà del mare, si può star certi che non la si rivedrà più. Il mare reclamerà a sé qualsiasi cosa gli venga consacrata in un modo o nell’altro, e ne riformerà le sembianze nel modo a lui più congeniale. Per intenderci, la magia delle sirene si dice origini dall’odio di una donna uccisa dal suo amante gettatala da una scogliera, che pure la amava. Per quanto suggestiva e melodrammatica, offre una panoramica di cosa potrebbe rappresentare. Ma non sono in molti a conoscere questa runa. Il più grande legame è col \[\[Mare dei Tesori\]\]

-        Difficoltà: 3 -        Rarità: 2
