---
title: "Sorgiva"
format:
  html:
    theme: default
---

Città dove vive la Prima Sacerdotessa che dà vita alle nuove sacerdotesse quando queste muoino per le città della costa Est di Miravia. Siccome ha un templio suo, un ordine a proteggerla, e tutte le sue figlie che sono molto longeve, a cui vengono cantate le Mille storie che contengono le conoscenze per il mondo delle acque, si considera memoria storica. 

Ali manora

Città su [[Croce dei Popoli]]

Uuna delle due città insieme a [[Linzia]] su  Croce dei Popoli. E come tale è strutturata. Le regine delle città di questa regione, tutte affacciate sul Mare, si dice siano protette da dagli [[Dèi]] oceanici.  Siccome essi possono cantare il linguaggio del mare, possono trasmettere messaggi tramite le balene. Cantando, vengono mandati messaggi alle altre città, messaggi di aiuto. E tramite altri canti in risposta, il mare si muove a loro protezione. Condivide questo tratto con [[Culto di Sorgiva]] , [[Navilla]] e [[Linzia]] 

Sempre ad Alì Manora è presente l'unica scuola di magia di [[Ordine dei maghi della nuova era|maghi da battaglia]] 

Linzia

Città su [[Croce dei Popoli]]

Linzia è una delle due città insieme a [[Ali Manora]] su  Croce dei Popoli. E come tale è strutturata. Le regine delle città di questa regione, tutte affacciate sul Mare, si dice siano protette da dagli [[Dèi]]
 oceanici.  Siccome essi possono cantare il linguaggio del mare, possono trasmettere messaggi tramite le balene. Cantando, vengono mandati messaggi alle altre città, messaggi di aiuto. E tramite altri canti in risposta, il mare si muove a loro protezione. 

L'altro motivo per la sua fama è l'[[Ordine dei maghi di Merlino]], che si dice sia stanziato lì vicino. 

Navilla

