---
title: "Lore dei Venatores"
search: false
format:
  html:
    theme: default
---

In antica memoria, praticamente una leggenda, esisteva si dice un regno abbastanza forte da essere stato in grado di resistere per molti secoli. Il re di questo regno, il [[Re Probo]], Fondò un ordine di cacciatori, perché riteneva che estirpando molti dei mali del mondo, di cui venne redatta una lista, almeno di quelli affrontabili dall'uomo, fosse possibile creare un mondo in cui vivere senza cataclismi che ogni 50 anni stravolgessero le città, e senza vivere alla mercé degli dei. 

Queste Creature sono ma non si limitano a:

- [[Draghi]]: i draghi andrebbero sottomessi. Bisognerebbe sottonettere i dragonidi, ma visto che non è possibile è necessario contenere il più possibile la loro più grande minaccia, cioè i draghi più giovani. I draghi più giovani sono più grandi, quindi devono essere abbattuti (aggiungerò specifiche al riguardo) 
- [[Elfi]]: bisogna instaurare con gli elfi un rapporto di collaborazione. Questo vedrà probabilmente dei conflitti, se necessario, ma con l'idea di arrivare a una tolleranza. Questo perché la longevità degli elfi è una risorsa che va sfruttata. 
- I demoni (cioè i [[Tiefling]]) bisogna che questa razza si rassegni che passati i 200/300 anni non sono più umani, ma vanno uccisi. Purtroppo non è anche chiaro come eliminare del tutto la minaccia, per il momento si procede tappando i buchi 
- Le [[Creature selvagge]]: le Creature selvaggie sono tutto quello che può venirti in mente alla voce Mostro (Basilisco, Lupo, Lupo mannaro, Viverne, Manticora, Grifone, serpente marino... Tutto qui dentro. Ciò con qui è impossibile comunicare propriamente, va eliminato) 
- I [[Vampiri]]: nonostante siano in grado di creare delle collettività governandole, le sfruttano, illudendole di una vita. Pertanto, per quanto siano ragionevoli e capaci di emotività, vanno eliminati (a meno che non si rassegnino a mangiare i nostri vecchi a un passo dalla morte, cosa che pare si rifiutino di fare).


## Codex Venator

La caccia a queste Creature prevede un codice di condotta, riassunto nei seguenti precetti (con fratello si intende chi appartiene all'ordine dei Venatores)

- Un cacciatore non ha famiglia 
- La caccia prima della giustizia 
- La preda prima di un fratello
- La vittima prima della preda 
- ogni aiuto alla caccia deve essere accettato 
- il primo sangue ha diritto alla preda 
- Chi combatte senza giudizio per vendicare un fratello, non deve essere aiutato 
- Tra la vita tua e quella del fratello, scegli liberamente 
- Tra la vita tua e quella della vittima, la tua 
- Le lotte tra fratelli sono vietati 
- tra la città e la preda, la città 
- Un fratello che trasgredisce il codice, non è più considerato un fratello

### Diventare un venator, il Tatuaggio 

Ogni Venator sceglie un allievo o più di uno, e lo addestra. Sono sempre alla ricerca di apprendisti, perché non hanno ovviamente tempo per una famiglia, e pertanto non hanno figli. Per riconoscersi tra Venatores, serve un Venatores. Due fratelli quando si guardano negli occhi si riconoscono, sempre. Che significa che non è così difficile ingannare dei non Venatores di essere tale, ma impossibile ingannare un fratello. Per il resto dei mortali c'è un taguaggio che ogni venator sceglie dove fare. 
Alla fine della loro carriera, un Venator diventa uno Stratega Anziano, una sorta di capo anziano, che aiuta  agestire l'amministrazione, le strategie, gli addestramenti e i Rifugi dei Vantores. 

### Rifugi dei Cacciatori (Le Tane) 

Nel corso dei secoli i Venatores hanno creato molte basi qua e là 

- Rifugi segreti nei boschi 
- Città che riconoscono l'ordine (per il tempo che durano le città, s'intende), si parla di locande che offrono rifugio gratuito, armerie eccetera 
- Alcune alleanze con alcuni gruppi di elfi

### Categorie dei Venatores

#### Cacciatore di Vampiri

Un cacciatore di [[Vampiri]] è addestrato nell'arte della caccia ai vampiri, alla quel dedica tutta la sua vita. 

Un cacciatore di vampiri possiede le seguenti abilità e strumenti:

- Percezione dell’aura: un venatores specializzato riconosce a occhio nudo quanta aura possiede un vampiro in una scala da 1 a 20. 20 non è il tetto massimo, è solo il tetto massimo percepibile dal cacciatore. 
- Percezione magia vampirica: può tirare per cercare di capire se il vampiro che ha di fronte può accedere all’aura di un mago (che sarebbe molto pericoloso, ovviamente)
- Possiede tra il suo equipaggiamento una spada o altra arma di argento.  (che tiene in un fodero che li maschera all’olfatto raffinato dei vampiri) (Le armi in argento triplicano il danno inferto ai vampiri)
- Possiede anche una catena di Argento di 12 metri, utile alle sue operazioni di caccia ai vampiri.
- Ha avuto la grazia di sviluppare l’immunità al loro specifico anestetico
- È in grado di creare un Cerchio: un perimetro entro il quale la capacità del vampiro di accedere all’aura è molto indebolita. Per attivarlo deve preparare con dei rituali magici che gli sono stati insegnati di cui non conosce il significato, ma sa replicarli. L’area si estende per una trentina di metri di raggio, e viene preparata in un paio di minuti.
- Tecniche di caccia condivise: se ha tanti aiuti, può utilizzare delle catene fatte in solo argento (dal costo molto molto elevato) per imprigionare un vampiro. Questo può avere molti benefici per reperire informazioni.
- Fiale di Veleno per vampiri (di quello autoiniettabile): se il vampiro ti beve mentre l’hai in corpo dovrebbe perdere conoscenza. Hai avuto la grazia di sviluppare l’immunità anche a questo veleno.

#### Cacciatore di Draghi

Il problema di affrontare i dragonidi è affrontare i draghi. Per affrontare i draghi i Venatores si sono attrezzati con il Sangue di drago 
Occorre un lungo addestramento per poter utilizzare il sangue di drago, in grado di migliorare le capacità fisiche e fornire Alcune capacità del drago al cacciatore. Più è grande il drago da cui si ottiene il drago, più forte è l'effetto. 

È importante notare che non c'è una gerarchia tra ventaores, solo alcuni che hanno assunto il ruolo di gestori. Tipicamente sono Venatores in pensione che contribuiscono alla causa facendo da organizzatori. 

Una cosa da ricordare dei draghi, è che questi mantengono le capacità che avevano prima di diventare draghi. Un drago può andare in Ira, usare attacco furtivo, non essere pedinabile... Questi sono i rischi di chi caccia i draghi. 

**Equipaggiamento** 

- Giacca di pelle di drago (la prima vittima che hai fatto), ignifuga, armatura media. 
- Dardi per balestra in [[Meteorite]] che hanno qualche porbabilità in più di perforare le scaglie dei draghi. 
- Arpione retrattile
- Inoltre, hai l'addestramento di primo livello per l'utilizzo del sangue di drago grezzo. Qualsiasi classe costruirai, avrai a disposizione tre boccette iniettabili col seguente effetto: "Per 5 turni ottieni le seguenti caratteristiche 
	- +30 punti ferita 
	- +4 ai tutti i danni inferti 
	- +2 ai tiri per colpire 
	- non puoi essere spaventato 

Una volta esaurite le boccette devi trovare un rifugio da Venatores e io vedo se te ne danno altro tirando. Come regola non ne si dà più di tre alla volta, perché sono molto costose. Ne puoi usare una per riposo breve. 

In realtà alcuni Venatores hanno anche sviluppato una tecnologia molto rischiosa: impiantarsi il cuore di un drago. Questo li rende in grado di grandissimi portenti, ma è per cacciatori folli, martiri della missione. Comunqueè necessario sapere come funzionano. Vedi [cardia draconis](/capitoli/Power-Up/altri/cuoredrago.qmd)


#### Cacciatore di Tiefling   

Ha in dotazione armi in [[Argento Bianco]]

Conosci la [Lore dei demoni](/capitoli/Lore/Approfondimenti/Lore%20Nascosta/demoni.html)
Conosci anche l'[Elenco dei Diavoli](/capitoli/Lore/Approfondimenti/Lore%20Nascosta/demoni/elencodemoni.qmd)

#### Cacciatore di Bestie

In quanto Venator, hai diritto a sconti nelle erboristerie per l'acquisto dei veleni (non per l'infuione) del 20%. Questo sconto non è automaticamente estendibile al resto del party (prove per mentire, l'erborista proverà a stimare se tu stia comprando una quantità ragionevole di veleno)

Hai studiato il [Bestiario](/capitoli/Lore/Approfondimenti/Lore%20Nascosta/creature.html). Questo ti dà la possibilità di 

- Conoscere il comportamento delle bestie. Se incontri una bestia, puoi tirare per provare a decifrare il loro comportamento. 
- Conoscere la collocazione del territorio. Se stai in un territorio per qualche ora, puoi capire chi è il predatore dominante con un tiro. Inoltre, il dm ti avvisa se il predatore cambia muovendoti in un'altra zona.

##### Atteggiamenti 
Gli atteggiamenti non sono specie specifici, spesso sono invece appresi, modellati sulla base di comportamenti di altri animali, o degli uomini intorno a loro. Come Venator sei in grado di identificarli

- **Sentinella innocua**
	- **Descrizione**: Sorvegli il territorio ma non attacca le creature  umanoidi se non provocata. Addirittura possibile avvicinarsi con la tecnica giusta fino ad accarezzarle. Così facendo sarebbe possbile anche parlare conla creatura.

- **Dormienti**
	- **Descrizione**: Innocua finché non viene svegliata, a quel punto è troppo tardi

- **Lotta di misura**
	- **Descrizione**: Cerca solo combattimenti frontali. Non attacca prede deboli o ferite, ma solo chi ritiene abbastanza forte. Se il suo contendente lotta un po' e poi perde o si arrende lo strapazza per dimostrare la sua superiorità e poi lo abandona. Se si riesce a sottometterlo invece diventerà obbediente nei confronti dell'avversario. 

- **Difensore Furente**
	- **Descrizione**: Attacca solo se provocata o se il suo territorio/cuccioli vengono minacciati. Una volta provocata, diventa estremamente pericolosa. Allontanarsi abbastanza se si tratta del territorio. Se si tratta dei cuccioli c'è poco da fare. Fingersi morti può facilmente essere un modo per salvarsi, la bestia ti porta a 1 pf svenuto.

- **Capo Branco**
	- **Descrizione**: Guida un branco e sfrutta la cooperazione. Spinge le prede in trappole, usa diversivi. Dividere il branco con esche o rumori. Eliminare i membri più deboli per indebolire la struttura. Mirare al capobranco.

- **Predatore Paziente**
	- **Descrizione**: Tende agguati silenziosi, si muove poco, osserva a lungo prima di attaccare. Colpisce con violenza, poi si ritira di nuovo. Tende ad attaccare prima i embri deboli di un gruppo. Forzare lo scontro aperto con rumore o fuoco. Attirarla fuori con esche vive o sanguinanti. 

- **Segugio Ossessivo**
	- **Descrizione**: Non smette di inseguire la preda finché non la elimina. Sembra ignorare il pericolo per completare la caccia. Usare la preda designata come esca. Tende a ignorare minacce laterali.

- **Opportunista**
	- **Descrizione**: Attacca solo se il vantaggio è certo. Evita i rischi e si nutre anche di carogne. Farla sentire al sicuro con apparenza di vulnerabilità. Appena si avvicina, colpirla con imboscate letali.

- **Trappolatrice**
	- **Descrizione**: Finge di essere ferita per fare abbassare la guardai agli assaltatori.

- **Imitatrice**
	- **Descrizione**: Imita i comportamenti di altri animali, tra le più difficili da identificare. Non abbassare la guardia nemmeno contro quello che si consoce

- **Caccia Ludica**
	- **Descrizione**: La bestia non caccia per fame, ma per divertimento. Gioca con la preda, la stanca, la tormenta. Fugge non appena il pericolo è reale. Mostrarsi aggressivi e pericolosi, fingere superiorità per spaventarla. Simulare ferite gravi per attirarla in trappola, poi colpire duramente. 

- **Collezionista Macabro**
	- **Descrizione**: Uccide per prendere trofei, o solo alcune parti della preda. Si ritira se ottiene quello che cerca. Lasciare falsi trofei o oggetti desiderabili per attirarla. Ingannarla sul fatto che la “preda” sia già stata predata.    

- **Venedicativa**
	- **Descrizione**: Ricorda chi l'ha ferita o minacciata. Segue a lungo, colpisce con precisione, e prende di mira specifici individui.

- **Aggressivo instabile**
	- **Descrizione**: Attacchi irrazionali e imprevedibili, motivati da una strana sete di Sangue. Potrebbe attaccare alleati o distruggere risorse senza motivo. Sfruttare la sua impulsività per portarlo su un campo di battaglia preparato. Evitare lo scontro se non si è preparati.

